Telnet-SML: SERDatabase Class Reference
SERDatabase Class Reference
SQLite database handler for storing and retrieving SER records.
#include <ser_database.hpp>
Public Member Functions
SERDatabase (const std::string &dbPath="ser_records.db")
Construct database handler with specified file path.
~SERDatabase ()
Destructor that closes the database connection.
bool open ()
Open database connection and initialize schema.
void close ()
Close database connection.
bool isOpen () const
Check if database is currently open.
bool insertRecord (const SERRecord &record)
Insert a single SER record into the database.
int insertRecords (const std::vector< SERRecord > &records)
Insert multiple SER records with transaction support.
std::vector< SERRecord > insertAndGetNewRecords (const std::vector< SERRecord > &records, int &insertedCount)
Insert records and return only the newly inserted ones.
std::vector< SERRecord > getAllRecords ()
Retrieve all SER records ordered by timestamp (newest first).
std::vector< SERRecord > getRecordsByStatus (const std::string &status)
Retrieve records filtered by status.
std::vector< SERRecord > getRecordsByRelay (const std::string &relayId)
Retrieve records filtered by relay identifier.
int getRecordCount ()
Get total count of records in the database.
bool clearAllRecords ()
Delete all records from the database.
bool exportToJSON (const std::string &filePath="ui/data.json")
Export all records to a JSON file for UI consumption.
const std::string & getLastError () const
Get last error message.
sqlite3 * getDbHandle () const
Get the raw SQLite database handle.
Non-copyable
SERDatabase (const SERDatabase &)=delete
SERDatabase & operator= (const SERDatabase &)=delete
Private Member Functions
bool createTable ()
Create SER records table and indexes.
bool recordExists (const std::string &relayId, const std::string &recordId, const std::string &timestamp)
Check if a record already exists in the database.
Private Attributes
std::string db_path_
Path to SQLite database file.
sqlite3 * db_
SQLite database handle (nullptr when closed).
std::string last_error_
Last error message for getLastError().
Detailed Description
SQLite database handler for storing and retrieving SER records.
Manages persistent storage of System Event Records using SQLite. Features:
Automatic database and table creation
Duplicate detection (skips existing record_id + timestamp combinations)
Transaction support for bulk inserts
Multiple query options (all, by status)
JSON export for web UI
Lifecycle
Invariant
db_ is either nullptr (closed) or valid SQLite handle
Table exists after successful open()
Definition at line 138 of file ser_database.hpp.
Constructor & Destructor Documentation
SERDatabase() [1/2]
SERDatabase::SERDatabase (const std::string & dbPath = "ser_records.db") explicit
Construct database handler with specified file path.
Construct a new SERDatabase with the specified file path.
Creates handler but does not open database. Call open() to establish connection. File will be created if it doesn't exist.
Parameters
dbPath Path to SQLite database file (default: "ser_records.db")
Postcondition
db_ == nullptr (not yet connected)
db_path_ == dbPath
Stores the database path for later use by open(). Does not open or create the SQLite file until open() is called.
Parameters
dbPath Filesystem path to the SQLite database file (e.g. "ser_records.db"). Created automatically by open() if it does not already exist.
Postcondition
db_ == nullptr (not yet connected)
Definition at line 48 of file ser_database.cpp.
References db_, and db_path_.
Referenced by operator=(), and SERDatabase().
~SERDatabase()
SERDatabase::~SERDatabase ()
Destructor that closes the database connection.
Destroy the SERDatabase and release all resources.
Calls close() to release SQLite resources.
Calls close() to finalize the SQLite handle if still open. Safe to call even if the database was never opened.
Definition at line 59 of file ser_database.cpp.
References close().
SERDatabase() [2/2]
SERDatabase::SERDatabase (const SERDatabase &) delete
References SERDatabase().
Member Function Documentation
clearAllRecords()
bool SERDatabase::clearAllRecords ()
Delete all records from the database.
Delete all SER records from the database.
Returns
true if records were cleared successfully
false if clear failed (check getLastError())
Precondition
isOpen() == true
Postcondition
getRecordCount() == 0
Executes DELETE FROM ser_records. The table structure and indexes remain intact; only data rows are removed.
Returns
true All records deleted successfully.
false Database not open or SQL error. Check getLastError().
Precondition
isOpen() == true
Warning
This operation cannot be undone. All historical SER data will be permanently lost.
Definition at line 558 of file ser_database.cpp.
References db_, and last_error_.
Referenced by operator=().
close()
void SERDatabase::close ()
Close database connection.
Close the SQLite database connection.
Releases SQLite handle. Safe to call multiple times.
Postcondition
isOpen() == false
db_ == nullptr
Finalizes the internal sqlite3 handle and sets db_ to nullptr. Safe to call multiple times; subsequent calls are no-ops.
Postcondition
db_ == nullptr, isOpen() == false.
Definition at line 120 of file ser_database.cpp.
References db_.
Referenced by operator=(), and ~SERDatabase().
createTable()
bool SERDatabase::createTable () private
Create SER records table and indexes.
Create the ser_records table and indexes if they do not exist.
Creates table with schema:
id: Auto-increment primary key
relay_id: Relay identifier (e.g., "1")
relay_name: Relay display name (e.g., "SEL-751")
record_id: Event number from relay
timestamp: Event date and time
status: Event state (Asserted/Deasserted/empty)
description: Event element/description
created_at: When record was stored
Also creates indexes on relay_id, record_id, status, and timestamp. Includes migration logic for existing databases without relay columns.
Returns
true if table was created or already exists
false if creation failed
Executes a multi-statement SQL that creates:
Table ser_records with columns: id, record_id, timestamp, status, description, created_at. A UNIQUE constraint on (record_id, timestamp) prevents duplicates.
Indexes on record_id, status, and timestamp for fast lookups.
Returns
true Schema created or already existed.
false SQL execution failed; last_error_ set.
Precondition
db_ != nullptr (called internally by open()).
Definition at line 156 of file ser_database.cpp.
References db_, and last_error_.
Referenced by open().
exportToJSON()
bool SERDatabase::exportToJSON (const std::string & filePath = "ui/data.json")
Export all records to a JSON file for UI consumption.
Export all SER records to a JSON file.
Generates a JSON array compatible with web UI format.
Output Format:
[
  {
    "sno": 45,
    "date": "02/14/22",
    "time": "12:47:19.970",
    "element": "Power loss",
    "state": ""
  },
  ...
]
Parameters
filePath Path to output JSON file (default: "ui/data.json")
Returns
true if export succeeded
false if export failed (check getLastError())
Precondition
isOpen() == true
Retrieves all records via getAllRecords() and writes them as a JSON array to the specified file. Each record object contains: sno, date, time, element, and state fields.
Special characters in the description field are escaped to produce valid JSON output.
Parameters
filePath Destination file path (e.g. "data.json"). Created or overwritten if it already exists.
Returns
true File written successfully.
false Database not open or file cannot be opened for writing. Check getLastError() for details.
Precondition
isOpen() == true
See also
SERJsonWriter Alternative streaming JSON writer.
Definition at line 640 of file ser_database.cpp.
References db_, getAllRecords(), and last_error_.
Referenced by operator=().
getAllRecords()
std::vector< SERRecord > SERDatabase::getAllRecords ()
Retrieve all SER records ordered by timestamp (newest first).
Retrieve all SER records ordered by timestamp (most recent first).
Returns
std::vector<SERRecord> All stored records, or empty if error/none
Precondition
isOpen() == true
Executes SELECT ... ORDER BY timestamp DESC and maps each row into a SERRecord struct. Returns an empty vector if the database is not open or the query fails.
Returns
std::vector<SERRecord> All stored records, newest first. Empty if database is closed or an error occurs.
Precondition
isOpen() == true
See also
getRecordsByStatus() Filtered version of this query.
Definition at line 355 of file ser_database.cpp.
References db_, SERRecord::description, last_error_, SERRecord::record_id, SERRecord::relay_id, SERRecord::relay_name, SERRecord::status, and SERRecord::timestamp.
Referenced by exportToJSON(), and operator=().
getDbHandle()
sqlite3 * SERDatabase::getDbHandle () const inline
Get the raw SQLite database handle.
Provides direct access to the underlying sqlite3 pointer for use by WSDBServer or other components needing generic DB access.
Returns
sqlite3* Raw handle (nullptr if not open)
Warning
Caller must not close or free this handle.
See also
WSDBServer
Definition at line 345 of file ser_database.hpp.
References db_.
getLastError()
const std::string & SERDatabase::getLastError () const
Get last error message.
Get the error message from the last failed operation.
Returns
const std::string& Error message from last failed operation
Set by any operation that fails (open, insert, query, export). Contains the SQLite error message or a custom description. Empty if no error has occurred.
Returns
const std::string& Reference to the last error message.
Definition at line 717 of file ser_database.cpp.
Referenced by operator=().
getRecordCount()
int SERDatabase::getRecordCount ()
Get total count of records in the database.
Get the total number of SER records in the database.
Returns
int Number of records, or 0 if error
Precondition
isOpen() == true
Executes SELECT COUNT(*) FROM ser_records.
Returns
int Number of rows, or 0 if the database is closed or the query fails.
Precondition
isOpen() == true
Definition at line 518 of file ser_database.cpp.
Referenced by operator=().
getRecordsByRelay()
std::vector< SERRecord > SERDatabase::getRecordsByRelay (const std::string & relayId)
Retrieve records filtered by relay identifier.
Retrieve SER records filtered by relay identifier.
Parameters
relayId Relay ID to filter by (e.g., "1", "2")
Returns
std::vector<SERRecord> Matching records ordered by timestamp
Precondition
isOpen() == true
Executes a parameterised query with WHERE relay_id = ? and returns results in descending timestamp order.
Parameters
relayId Relay identifier to match (e.g. "1", "2").
Returns
std::vector<SERRecord> Matching records, newest first. Empty if none match, database is closed, or query fails.
Precondition
isOpen() == true
Definition at line 465 of file ser_database.cpp.
Referenced by operator=().
getRecordsByStatus()
std::vector< SERRecord > SERDatabase::getRecordsByStatus (const std::string & status)
Retrieve records filtered by status.
Retrieve SER records filtered by status value.
Parameters
status Status to filter by (e.g., "Asserted", "Deasserted")
Returns
std::vector<SERRecord> Matching records ordered by timestamp
Precondition
isOpen() == true
Executes a parameterised query with WHERE status = ? and returns results in descending timestamp order.
Parameters
status Status string to match (e.g. "ASSERTED", "DEASSERTED").
Returns
std::vector<SERRecord> Matching records, newest first. Empty if none match, database is closed, or query fails.
Precondition
isOpen() == true
Definition at line 409 of file ser_database.cpp.
Referenced by operator=().
insertAndGetNewRecords()
std::vector< SERRecord > SERDatabase::insertAndGetNewRecords (const std::vector< SERRecord > & records, int & insertedCount)
Insert records and return only the newly inserted ones.
Inserts all records within a transaction, skips duplicates, and returns a vector containing only the records that were actually stored (not already present in the database).
Parameters
records Vector of SER records to insert
[out] insertedCount Number of records inserted
Returns
std::vector<SERRecord> Only the records that were newly inserted
Precondition
isOpen() == true
Wraps all inserts in a single transaction. For each record, checks whether it already exists before inserting. Only records that did not previously exist and were successfully inserted are included in the returned vector.
Parameters
records Vector of SERRecord objects to insert.
insertedCount [out] Number of records actually inserted.
Returns
std::vector<SERRecord> Records that were newly inserted (not duplicates).
Precondition
isOpen() == true
Definition at line 307 of file ser_database.cpp.
References db_, insertRecord(), last_error_, and recordExists().
Referenced by operator=().
insertRecord()
bool SERDatabase::insertRecord (const SERRecord & record)
Insert a single SER record into the database.
Inserts record if not already present (by record_id + timestamp). Duplicate records are silently skipped (returns true).
Parameters
record The SER record to insert
Returns
true if record was inserted or already exists
false if insert failed (check getLastError())
Precondition
isOpen() == true
First calls recordExists() to check for duplicates on (record_id, timestamp). If the record already exists it returns true (skip, not an error). Otherwise it prepares an INSERT statement with parameter binding for safety.
Parameters
record The SERRecord to insert. All four fields (record_id, timestamp, status, description) are stored.
Returns
true Record inserted or already existed (duplicate skip).
false Database not open, prepare failed, or step failed. Check getLastError() for details.
Precondition
isOpen() == true
See also
insertRecords() Bulk insert with transaction wrapping.
recordExists() Duplicate detection helper.
Definition at line 203 of file ser_database.cpp.
References db_, SERRecord::description, last_error_, SERRecord::record_id, recordExists(), SERRecord::relay_id, SERRecord::relay_name, SERRecord::status, and SERRecord::timestamp.
Referenced by insertAndGetNewRecords(), insertRecords(), and operator=().
insertRecords()
int SERDatabase::insertRecords (const std::vector< SERRecord > & records)
Insert multiple SER records with transaction support.
Bulk-insert a vector of SER records inside a single transaction.
Inserts all records within a transaction for better performance. Skips duplicates and continues with remaining records.
Parameters
records Vector of SER records to insert
Returns
int Number of records successfully inserted (0 to records.size())
Precondition
isOpen() == true
Note
Uses BEGIN/COMMIT transaction for performance
Duplicates are counted as "success" (not errors)
Wraps all inserts in BEGIN TRANSACTION / COMMIT for significantly better performance on large batches. Each record is inserted via insertRecord(), so duplicates are silently skipped.
Parameters
records Vector of SERRecord objects to insert.
Returns
int Number of records successfully inserted (excludes duplicates). Returns 0 if the database is not open.
Precondition
isOpen() == true
Note
The entire batch is committed even if some individual inserts are skipped as duplicates.
Definition at line 266 of file ser_database.cpp.
References db_, insertRecord(), and last_error_.
Referenced by PollSerAction::operator()(), and operator=().
isOpen()
bool SERDatabase::isOpen () const
Check if database is currently open.
Check whether the database connection is currently open.
Returns
true if database connection is active
false if database is closed
true Database is open and ready for queries.
false Database is closed.
Definition at line 135 of file ser_database.cpp.
References db_.
Referenced by operator=().
open()
bool SERDatabase::open ()
Open database connection and initialize schema.
Open the SQLite database and create the schema if needed.
Opens SQLite database file and creates table if not exists. Also creates indexes for efficient querying.
Returns
true if database opened and table created successfully
false if open or create failed (check getLastError())
Postcondition
On success: isOpen() == true, table exists
On failure: isOpen() == false, last_error_ contains message
See also
createTable() Internal table creation
Performs the following steps:
If already open, returns true immediately (idempotent).
Calls sqlite3_open() to create/open the database file.
Invokes createTable() to ensure the ser_records table and its indexes exist.
Returns
true Database opened (or was already open) and schema ready.
false sqlite3_open() or createTable() failed. Check getLastError() for details.
Postcondition
On success: db_ != nullptr, isOpen() == true.
On failure: db_ == nullptr, last_error_ set.
See also
close() Release the connection when done.
createTable() Internal schema initialisation.
Definition at line 85 of file ser_database.cpp.
References createTable(), db_, db_path_, and last_error_.
Referenced by operator=().
operator=()
SERDatabase & SERDatabase::operator= (const SERDatabase &) delete
References clearAllRecords(), close(), exportToJSON(), getAllRecords(), getLastError(), getRecordCount(), getRecordsByRelay(), getRecordsByStatus(), insertAndGetNewRecords(), insertRecord(), insertRecords(), isOpen(), open(), and SERDatabase().
recordExists()
bool SERDatabase::recordExists (const std::string & relayId, const std::string & recordId, const std::string & timestamp) private
Check if a record already exists in the database.
Check whether a record with the given relay ID, record ID and timestamp already exists.
Parameters
relayId Relay identifier
recordId Record ID to check
timestamp Timestamp to check
Returns
true if record with same relay_id + record_id + timestamp exists
false if record not found
Uses a SELECT 1 ... LIMIT 1 query for minimal overhead. Called internally by insertRecord() to prevent duplicates.
Parameters
relayId The relay identifier to look up.
recordId The record identifier to look up.
timestamp The timestamp to match against.
Returns
true A matching row exists.
false No match found, or the query failed.
Definition at line 595 of file ser_database.cpp.
References db_.
Referenced by insertAndGetNewRecords(), and insertRecord().
Member Data Documentation
db_
sqlite3* SERDatabase::db_ private
SQLite database handle (nullptr when closed).
Definition at line 383 of file ser_database.hpp.
Referenced by clearAllRecords(), close(), createTable(), exportToJSON(), getAllRecords(), getDbHandle(), insertAndGetNewRecords(), insertRecord(), insertRecords(), isOpen(), open(), recordExists(), and SERDatabase().
db_path_
std::string SERDatabase::db_path_ private
Path to SQLite database file.
Definition at line 382 of file ser_database.hpp.
Referenced by open(), and SERDatabase().
last_error_
std::string SERDatabase::last_error_ private
Last error message for getLastError().
Definition at line 384 of file ser_database.hpp.
Referenced by clearAllRecords(), createTable(), exportToJSON(), getAllRecords(), insertAndGetNewRecords(), insertRecord(), insertRecords(), and open().
The documentation for this class was generated from the following files:
ser_database.hpp
ser_database.cpp