Telnet-SML: TelnetSmlApp Class Reference
TelnetSmlApp Class Reference
Main application facade for the Telnet-SML system.
#include <telnet_sml_app.hpp>
Classes
class Impl
Private implementation (PIMPL) of TelnetSmlApp.
Public Member Functions
TelnetSmlApp ()
Construct a TelnetSmlApp instance.
~TelnetSmlApp ()
Destroy the TelnetSmlApp instance.
bool start ()
Start the application and all background threads.
void waitForExit ()
Block until user requests application exit.
void stop ()
Stop the application and all background threads.
bool isRunning () const
Check if the application is currently running.
Deleted Copy/Move Operations
TelnetSmlApp (const TelnetSmlApp &)=delete
TelnetSmlApp & operator= (const TelnetSmlApp &)=delete
TelnetSmlApp (TelnetSmlApp &&)=delete
TelnetSmlApp & operator= (TelnetSmlApp &&)=delete
Private Attributes
std::unique_ptr< Impl > impl_
Forward declaration of implementation.
Detailed Description
Main application facade for the Telnet-SML system.
Provides a simplified interface for the multi-threaded Telnet-SML application. Uses the PIMPL idiom to hide implementation details and maintain ABI stability.
Lifecycle
Invariant
impl_ is always valid after construction
Thread-safe for single-threaded control (start/stop/wait)
Note
Non-copyable and non-movable to prevent resource confusion
Definition at line 113 of file telnet_sml_app.hpp.
Constructor & Destructor Documentation
TelnetSmlApp() [1/3]
TelnetSmlApp::TelnetSmlApp ()
Construct a TelnetSmlApp instance.
Constructs a TelnetSmlApp instance.
Creates the private implementation but does not start any background threads. Call start() to begin operation.
Postcondition
isRunning() == false
Creates the private implementation (PIMPL) object. No connections are made until start() is called.
Definition at line 1048 of file telnet_sml_app.cpp.
References impl_.
Referenced by operator=(), operator=(), TelnetSmlApp(), and TelnetSmlApp().
~TelnetSmlApp()
TelnetSmlApp::~TelnetSmlApp ()
Destroy the TelnetSmlApp instance.
Destroys the TelnetSmlApp instance.
Ensures graceful shutdown by calling stop() if still running.
Definition at line 1057 of file telnet_sml_app.cpp.
References impl_.
TelnetSmlApp() [2/3]
TelnetSmlApp::TelnetSmlApp (const TelnetSmlApp &) delete
References TelnetSmlApp().
TelnetSmlApp() [3/3]
TelnetSmlApp::TelnetSmlApp (TelnetSmlApp &&) delete
References TelnetSmlApp().
Member Function Documentation
isRunning()
bool TelnetSmlApp::isRunning () const
Check if the application is currently running.
Checks if the application is currently running.
Returns
true if the application is running
false if the application is stopped
true if running, false otherwise
Definition at line 1106 of file telnet_sml_app.cpp.
References impl_.
Referenced by operator=().
operator=() [1/2]
TelnetSmlApp & TelnetSmlApp::operator= (const TelnetSmlApp &) delete
References TelnetSmlApp().
operator=() [2/2]
TelnetSmlApp & TelnetSmlApp::operator= (TelnetSmlApp &&) delete
References isRunning(), start(), stop(), TelnetSmlApp(), and waitForExit().
start()
bool TelnetSmlApp::start ()
Start the application and all background threads.
Starts the Telnet-SML application.
Initializes and starts:
SQLite database connection
WebSocket server (port 8765)
Reception worker thread
Processing worker thread
Polling scheduler
JSON file writer
Returns
true if all components started successfully
false if startup failed (see console for details)
Precondition
isRunning() == false
Postcondition
On success: isRunning() == true
Initializes and starts all components:
Database connection
WebSocket server
Worker threads (Reception, Processing, SHM Reader)
Polling thread
Returns
true on success, false if initialization fails
Definition at line 1074 of file telnet_sml_app.cpp.
References impl_.
Referenced by main(), and operator=().
stop()
void TelnetSmlApp::stop ()
Stop the application and all background threads.
Stops the Telnet-SML application.
Gracefully shuts down all components in reverse order. Safe to call multiple times or even if not started.
Postcondition
isRunning() == false
Gracefully shuts down all components in reverse order. Safe to call multiple times.
Definition at line 1096 of file telnet_sml_app.cpp.
References impl_.
Referenced by main(), and operator=().
waitForExit()
void TelnetSmlApp::waitForExit ()
Block until user requests application exit.
Waits for user to request application exit.
Waits for Enter key press. Typically called from main() after start() returns successfully.
Precondition
isRunning() == true
Blocks the calling thread until Enter key is pressed. Typically called from main() after start().
Definition at line 1085 of file telnet_sml_app.cpp.
References impl_.
Referenced by main(), and operator=().
Member Data Documentation
impl_
std::unique_ptr<Impl> TelnetSmlApp::impl_ private
Forward declaration of implementation.
PIMPL pointer to implementation
Definition at line 190 of file telnet_sml_app.hpp.
Referenced by isRunning(), start(), stop(), TelnetSmlApp(), waitForExit(), and ~TelnetSmlApp().
The documentation for this class was generated from the following files:
telnet_sml_app.hpp
telnet_sml_app.cpp