Telnet-SML: WebSocketListener Class Reference
WebSocketListener Class Reference
Listens for and accepts incoming WebSocket connections.
#include <ws_server.hpp>
Public Member Functions
WebSocketListener (net::io_context &ioc, tcp::endpoint endpoint, SERDatabase &db, SessionManager *sessionMgr=nullptr)
Construct listener on specified endpoint.
void run ()
Start the accept loop.
Private Member Functions
void do_accept ()
Initiate async accept for next connection.
void on_accept (beast::error_code ec, tcp::socket socket)
Handle accepted connection.
Private Attributes
net::io_context & ioc_
Reference to I/O context.
tcp::acceptor acceptor_
TCP acceptor for incoming connections.
SERDatabase & db_
Reference to database for sessions.
SessionManager * sessionMgr_
Session manager for broadcast support.
Detailed Description
Listens for and accepts incoming WebSocket connections.
Manages the TCP acceptor and creates WebSocketSession instances for each incoming connection. Runs continuously accepting connections.
Accept Loop
Definition at line 581 of file ws_server.hpp.
Constructor & Destructor Documentation
WebSocketListener()
WebSocketListener::WebSocketListener (net::io_context & ioc, tcp::endpoint endpoint, SERDatabase & db, SessionManager * sessionMgr = nullptr) inline
Construct listener on specified endpoint.
Parameters
ioc I/O context for async operations
endpoint TCP endpoint to listen on (address + port)
db Database reference to pass to sessions
sessionMgr Session manager for broadcast (may be null)
Definition at line 597 of file ws_server.hpp.
References acceptor_, db_, ioc_, and sessionMgr_.
Member Function Documentation
do_accept()
void WebSocketListener::do_accept () inline private
Initiate async accept for next connection.
Definition at line 652 of file ws_server.hpp.
References acceptor_, ioc_, and on_accept().
Referenced by on_accept(), and run().
on_accept()
void WebSocketListener::on_accept (beast::error_code ec, tcp::socket socket) inline private
Handle accepted connection.
Parameters
ec Error code from accept operation
socket Accepted TCP socket
Definition at line 665 of file ws_server.hpp.
References db_, do_accept(), and sessionMgr_.
Referenced by do_accept().
run()
void WebSocketListener::run () inline
Start the accept loop.
Begins accepting incoming connections. Called after constructor.
Definition at line 643 of file ws_server.hpp.
References do_accept().
Member Data Documentation
acceptor_
tcp::acceptor WebSocketListener::acceptor_ private
TCP acceptor for incoming connections.
Definition at line 584 of file ws_server.hpp.
Referenced by do_accept(), and WebSocketListener().
db_
SERDatabase& WebSocketListener::db_ private
Reference to database for sessions.
Definition at line 585 of file ws_server.hpp.
Referenced by on_accept(), and WebSocketListener().
ioc_
net::io_context& WebSocketListener::ioc_ private
Reference to I/O context.
Definition at line 583 of file ws_server.hpp.
Referenced by do_accept(), and WebSocketListener().
sessionMgr_
SessionManager* WebSocketListener::sessionMgr_ private
Session manager for broadcast support.
Definition at line 586 of file ws_server.hpp.
Referenced by on_accept(), and WebSocketListener().
The documentation for this class was generated from the following file:
ws_server.hpp