Telnet-SML: SERPoller Class Reference
SERPoller Class Reference
Periodic SER data polling thread.
#include <thread_manager.hpp>
Public Member Functions
SERPoller (std::chrono::seconds interval=std::chrono::seconds(30))
Construct SER poller.
~SERPoller ()
Destructor that stops the polling thread.
void setCallback (std::function< void()> callback)
Set the callback to execute on each poll.
void start ()
Start the polling thread.
void stop ()
Stop the polling thread.
bool isRunning () const
Check if poller is running.
void setInterval (std::chrono::seconds interval)
Set polling interval.
Private Attributes
std::thread poller_thread_
Polling thread.
std::atomic< bool > stop_flag_ {false}
Shutdown flag.
std::chrono::seconds poll_interval_
Interval between polls.
std::function< void()> poll_callback_
Function to call on each poll.
Detailed Description
Periodic SER data polling thread.
Runs a background thread that periodically triggers SER data fetching from the relay. This enables continuous monitoring without blocking the main application.
Polling Cycle
Definition at line 288 of file thread_manager.hpp.
Constructor & Destructor Documentation
SERPoller()
SERPoller::SERPoller (std::chrono::seconds interval = std::chrono::seconds(30)) inline explicit
Construct SER poller.
Parameters
interval Seconds between polls (default: 30)
Definition at line 300 of file thread_manager.hpp.
References poll_interval_.
~SERPoller()
SERPoller::~SERPoller () inline
Destructor that stops the polling thread.
Definition at line 308 of file thread_manager.hpp.
References stop().
Member Function Documentation
isRunning()
bool SERPoller::isRunning () const inline
Check if poller is running.
Returns
true if running
Definition at line 372 of file thread_manager.hpp.
References stop_flag_.
setCallback()
void SERPoller::setCallback (std::function< void()> callback) inline
Set the callback to execute on each poll.
Parameters
callback Function to call (e.g., FSM trigger)
Definition at line 317 of file thread_manager.hpp.
References poll_callback_.
setInterval()
void SERPoller::setInterval (std::chrono::seconds interval) inline
Set polling interval.
Parameters
interval New interval in seconds
Definition at line 378 of file thread_manager.hpp.
References poll_interval_.
start()
void SERPoller::start () inline
Start the polling thread.
Definition at line 325 of file thread_manager.hpp.
References poll_callback_, poll_interval_, poller_thread_, and stop_flag_.
stop()
void SERPoller::stop () inline
Stop the polling thread.
Definition at line 360 of file thread_manager.hpp.
References poller_thread_, and stop_flag_.
Referenced by ~SERPoller().
Member Data Documentation
poll_callback_
std::function<void()> SERPoller::poll_callback_ private
Function to call on each poll.
Definition at line 293 of file thread_manager.hpp.
Referenced by setCallback(), and start().
poll_interval_
std::chrono::seconds SERPoller::poll_interval_ private
Interval between polls.
Definition at line 292 of file thread_manager.hpp.
Referenced by SERPoller(), setInterval(), and start().
poller_thread_
std::thread SERPoller::poller_thread_ private
Polling thread.
Definition at line 290 of file thread_manager.hpp.
Referenced by start(), and stop().
stop_flag_
std::atomic<bool> SERPoller::stop_flag_ {false} private
Shutdown flag.
Definition at line 291 of file thread_manager.hpp.
Referenced by isRunning(), start(), and stop().
The documentation for this class was generated from the following file:
thread_manager.hpp