Telnet-SML: WebSocketSession Class Reference
WebSocketSession Class Reference
Handles a single WebSocket client connection.
#include <ws_server.hpp>
Classes
struct PendingMsg
Pending message: binary payload or text string, with mode flag.
Public Types
using CommandHandler = std::function<std::string(const std::string&)>
using ActionHandler = std::function<std::string(const std::string&)>
using StreamingCallback = std::function<void(const std::string&)>
using StreamCommandHandler
Public Member Functions
WebSocketSession (tcp::socket &&socket, SERDatabase &db, SessionManager *sessionMgr=nullptr, CommandHandler cmdHandler=nullptr, ActionHandler actionHandler=nullptr, StreamCommandHandler streamCmdHandler=nullptr)
Construct WebSocket session from accepted socket.
~WebSocketSession ()
Destructor - unregister from session manager.
void sendBroadcast (const std::vector< uint8_t > &data)
Send data to this client (for broadcast push).
void sendTextBroadcast (const std::string &text)
Send text data to this client (for non-SER command responses).
void run ()
Start the session by accepting WebSocket handshake.
Private Member Functions
void on_accept (beast::error_code ec)
Handle WebSocket handshake completion.
void do_broadcast (const std::vector< uint8_t > &data)
Perform broadcast write operation (called on strand).
void on_broadcast_write (beast::error_code ec, std::size_t)
Handle broadcast write completion — drains pending queue.
void drainQueue ()
Send the next queued message (if any).
void do_read ()
Initiate async read for next client message.
void on_read (beast::error_code ec, std::size_t bytes_transferred)
Handle received client message.
void sendData ()
Send current database records to client as ASN.1 BER/TLV.
void on_write (beast::error_code ec, std::size_t bytes_transferred)
Handle write completion.
void sendTextResponse (const std::string &text)
Send a plain text response to this client (for FIL DIR etc.).
Static Private Member Functions
static bool isJsonAction (const std::string &msg)
Check if a message is a JSON action (contains "action" key).
static std::string extractAction (const std::string &json)
Extract the "action" value from a simple JSON object.
Private Attributes
websocket::stream< beast::tcp_stream > ws_
WebSocket stream over TCP.
beast::flat_buffer buffer_
Buffer for incoming messages.
SERDatabase & db_
Reference to database for queries.
SessionManager * sessionMgr_
Session manager for registration.
bool writing_ = false
Flag to prevent concurrent writes.
bool pending_read_ = false
Flag for pending read after write.
std::vector< uint8_t > write_buffer_
Buffer to hold data during async write.
std::vector< uint8_t > broadcast_buffer_
Buffer for broadcast data.
std::string text_write_buffer_
Buffer for text responses (FIL DIR etc.).
CommandHandler cmdHandler_
Optional handler for relay commands.
ActionHandler actionHandler_
Optional handler for JSON actions (time sync).
StreamCommandHandler streamCmdHandler_
Optional handler for streaming commands.
std::atomic< bool > streaming_abort_ {false}
Abort flag for in-flight streaming.
std::deque< PendingMsg > write_queue_
Queued writes while a write is in-flight.
Detailed Description
Handles a single WebSocket client connection.
Manages the lifecycle of a WebSocket session:
Accepts WebSocket handshake
Sends initial data upon connection
Listens for client messages (e.g., "refresh")
Responds with current database records as ASN.1 BER/TLV
Uses shared_from_this() pattern for safe async callback handling.
Session Lifecycle
Definition at line 316 of file ws_server.hpp.
Member Typedef Documentation
ActionHandler
using WebSocketSession::ActionHandler = std::function<std::string(const std::string&)>
Callback type for JSON action handling (time sync etc.): input = action string (e.g. "read_time", "sync_time") output = JSON response string
Definition at line 327 of file ws_server.hpp.
CommandHandler
using WebSocketSession::CommandHandler = std::function<std::string(const std::string&)>
Callback type for relay command forwarding: input = command string (e.g. "FIL DIR") output = relay response text
Definition at line 322 of file ws_server.hpp.
StreamCommandHandler
using WebSocketSession::StreamCommandHandler
Initial value:
 std::function<bool(
        const std::string& cmd, StreamingCallback sendFn, std::atomic<bool>& abort)>
Definition at line 334 of file ws_server.hpp.
StreamingCallback
using WebSocketSession::StreamingCallback = std::function<void(const std::string&)>
Callback type for streaming commands (e.g. FETCH_ALL_TAR). Receives the raw command, a callback to send each streamed message, and an abort flag. Returns true if the command was handled as a stream, false to fall through to the normal single-response handler.
Definition at line 333 of file ws_server.hpp.
Constructor & Destructor Documentation
WebSocketSession()
WebSocketSession::WebSocketSession (tcp::socket && socket, SERDatabase & db, SessionManager * sessionMgr = nullptr, CommandHandler cmdHandler = nullptr, ActionHandler actionHandler = nullptr, StreamCommandHandler streamCmdHandler = nullptr) inline explicit
Construct WebSocket session from accepted socket.
Parameters
socket TCP socket from accepted connection (moved)
db Reference to SER database for data access
sessionMgr Pointer to session manager (may be null for legacy mode)
cmdHandler Optional callback for relay command forwarding
actionHandler Optional callback for JSON action handling (time sync)
Definition at line 372 of file ws_server.hpp.
References actionHandler_, cmdHandler_, db_, sessionMgr_, streamCmdHandler_, and ws_.
~WebSocketSession()
WebSocketSession::~WebSocketSession () inline
Destructor - unregister from session manager.
Definition at line 389 of file ws_server.hpp.
Member Function Documentation
do_broadcast()
void WebSocketSession::do_broadcast (const std::vector< uint8_t > & data) inline private
Perform broadcast write operation (called on strand).
If a write is already in progress, the payload is queued. The queue is drained automatically when the current write completes.
Definition at line 480 of file ws_server.hpp.
References WebSocketSession::PendingMsg::Binary, broadcast_buffer_, on_broadcast_write(), write_queue_, writing_, and ws_.
do_read()
void WebSocketSession::do_read () inline private
Initiate async read for next client message.
Definition at line 559 of file ws_server.hpp.
References buffer_, on_read(), and ws_.
Referenced by on_read(), and on_write().
drainQueue()
void WebSocketSession::drainQueue () inline private
Send the next queued message (if any).
Called after every successful write to flush pending data.
Definition at line 520 of file ws_server.hpp.
References WebSocketSession::PendingMsg::Binary, broadcast_buffer_, on_broadcast_write(), WebSocketSession::PendingMsg::SendAll, sendData(), WebSocketSession::PendingMsg::Text, text_write_buffer_, write_queue_, writing_, and ws_.
Referenced by on_broadcast_write(), and on_write().
extractAction()
std::string WebSocketSession::extractAction (const std::string & json) inline static private
Extract the "action" value from a simple JSON object.
Lightweight parser — no dependency on a JSON library.
Definition at line 747 of file ws_server.hpp.
Referenced by on_read().
isJsonAction()
bool WebSocketSession::isJsonAction (const std::string & msg) inline static private
Check if a message is a JSON action (contains "action" key).
Definition at line 735 of file ws_server.hpp.
Referenced by on_read().
on_accept()
void WebSocketSession::on_accept (beast::error_code ec) inline private
Handle WebSocket handshake completion.
Parameters
ec Error code from handshake (empty on success)
Definition at line 455 of file ws_server.hpp.
References pending_read_, sendData(), and sessionMgr_.
Referenced by run().
on_broadcast_write()
void WebSocketSession::on_broadcast_write (beast::error_code ec, std::size_t) inline private
Handle broadcast write completion — drains pending queue.
Definition at line 501 of file ws_server.hpp.
References drainQueue(), write_queue_, and writing_.
Referenced by do_broadcast(), and drainQueue().
on_read()
void WebSocketSession::on_read (beast::error_code ec, std::size_t bytes_transferred) inline private
Handle received client message.
Parameters
ec Error code from read operation
bytes_transferred Number of bytes received
Definition at line 572 of file ws_server.hpp.
References actionHandler_, buffer_, cmdHandler_, do_read(), extractAction(), isJsonAction(), pending_read_, sendData(), sessionMgr_, streamCmdHandler_, and streaming_abort_.
Referenced by do_read().
on_write()
void WebSocketSession::on_write (beast::error_code ec, std::size_t bytes_transferred) inline private
Handle write completion.
Parameters
ec Error code from write operation
bytes_transferred Number of bytes written
Definition at line 707 of file ws_server.hpp.
References do_read(), drainQueue(), pending_read_, streaming_abort_, write_queue_, and writing_.
Referenced by sendData(), and sendTextResponse().
run()
void WebSocketSession::run () inline
Start the session by accepting WebSocket handshake.
Configures timeout and server decorator, then initiates async WebSocket handshake acceptance.
Definition at line 433 of file ws_server.hpp.
References on_accept(), and ws_.
sendBroadcast()
void WebSocketSession::sendBroadcast (const std::vector< uint8_t > & data) inline
Send data to this client (for broadcast push).
Called by SessionManager to push data to connected clients. Thread-safe via strand posting.
Parameters
data Binary data to send (ASN.1 BER/TLV encoded)
Definition at line 403 of file ws_server.hpp.
References ws_.
sendData()
void WebSocketSession::sendData () inline private
Send current database records to client as ASN.1 BER/TLV.
Queries all records from database and sends as binary. If a write is in-flight the request is queued and sent later.
Definition at line 681 of file ws_server.hpp.
References db_, asn_tlv::encodeSerRecordsToTlv(), on_write(), WebSocketSession::PendingMsg::SendAll, write_buffer_, write_queue_, writing_, and ws_.
Referenced by drainQueue(), on_accept(), and on_read().
sendTextBroadcast()
void WebSocketSession::sendTextBroadcast (const std::string & text) inline
Send text data to this client (for non-SER command responses).
Called by SERWebSocketServer::broadcastText() to push raw relay text responses (e.g. FIL DIR) to connected clients. Thread-safe via strand posting.
Parameters
text Text data to send
Definition at line 420 of file ws_server.hpp.
References ws_.
sendTextResponse()
void WebSocketSession::sendTextResponse (const std::string & text) inline private
Send a plain text response to this client (for FIL DIR etc.).
Parameters
text The text response string to send
Definition at line 766 of file ws_server.hpp.
References on_write(), WebSocketSession::PendingMsg::Text, text_write_buffer_, write_queue_, writing_, and ws_.
Member Data Documentation
actionHandler_
ActionHandler WebSocketSession::actionHandler_ private
Optional handler for JSON actions (time sync).
Definition at line 348 of file ws_server.hpp.
Referenced by on_read(), and WebSocketSession().
broadcast_buffer_
std::vector<uint8_t> WebSocketSession::broadcast_buffer_ private
Buffer for broadcast data.
Definition at line 345 of file ws_server.hpp.
Referenced by do_broadcast(), and drainQueue().
buffer_
beast::flat_buffer WebSocketSession::buffer_ private
Buffer for incoming messages.
Definition at line 339 of file ws_server.hpp.
Referenced by do_read(), and on_read().
cmdHandler_
CommandHandler WebSocketSession::cmdHandler_ private
Optional handler for relay commands.
Definition at line 347 of file ws_server.hpp.
Referenced by on_read(), and WebSocketSession().
db_
SERDatabase& WebSocketSession::db_ private
Reference to database for queries.
Definition at line 340 of file ws_server.hpp.
Referenced by sendData(), and WebSocketSession().
pending_read_
bool WebSocketSession::pending_read_ = false private
Flag for pending read after write.
Definition at line 343 of file ws_server.hpp.
Referenced by on_accept(), on_read(), and on_write().
sessionMgr_
SessionManager* WebSocketSession::sessionMgr_ private
Session manager for registration.
Definition at line 341 of file ws_server.hpp.
Referenced by on_accept(), on_read(), and WebSocketSession().
streamCmdHandler_
StreamCommandHandler WebSocketSession::streamCmdHandler_ private
Optional handler for streaming commands.
Definition at line 349 of file ws_server.hpp.
Referenced by on_read(), and WebSocketSession().
streaming_abort_
std::atomic<bool> WebSocketSession::streaming_abort_ {false} private
Abort flag for in-flight streaming.
Definition at line 350 of file ws_server.hpp.
Referenced by on_read(), and on_write().
text_write_buffer_
std::string WebSocketSession::text_write_buffer_ private
Buffer for text responses (FIL DIR etc.).
Definition at line 346 of file ws_server.hpp.
Referenced by drainQueue(), and sendTextResponse().
write_buffer_
std::vector<uint8_t> WebSocketSession::write_buffer_ private
Buffer to hold data during async write.
Definition at line 344 of file ws_server.hpp.
Referenced by sendData().
write_queue_
std::deque<PendingMsg> WebSocketSession::write_queue_ private
Queued writes while a write is in-flight.
Definition at line 360 of file ws_server.hpp.
Referenced by do_broadcast(), drainQueue(), on_broadcast_write(), on_write(), sendData(), and sendTextResponse().
writing_
bool WebSocketSession::writing_ = false private
Flag to prevent concurrent writes.
Definition at line 342 of file ws_server.hpp.
Referenced by do_broadcast(), drainQueue(), on_broadcast_write(), on_write(), sendData(), and sendTextResponse().
ws_
websocket::stream<beast::tcp_stream> WebSocketSession::ws_ private
WebSocket stream over TCP.
Definition at line 338 of file ws_server.hpp.
Referenced by do_broadcast(), do_read(), drainQueue(), run(), sendBroadcast(), sendData(), sendTextBroadcast(), sendTextResponse(), and WebSocketSession().
The documentation for this class was generated from the following file:
ws_server.hpp