Telnet-SML: TelnetClient Class Reference
TelnetClient Class Reference
TCP/Telnet client for substation relay communication.
#include <client.hpp>
Public Member Functions
TelnetClient ()
Construct a new TelnetClient object.
bool connectCheck (const std::string &host, int port, std::chrono::milliseconds timeout)
Connect to a Telnet server with timeout.
bool isConnected () const
Check if client is currently connected.
bool SendCmdReceiveData (const std::string &cmd, std::string &outBuffer)
Send command and receive response data.
bool LoginLevel1Function (const std::string &username, const std::string &password)
Perform Level 1 login authentication.
const std::string & getLastResponse () const
Get the last response received.
bool getLastIoResult () const
Get the result of the last I/O operation.
void clearLastResponse ()
Clear the last response buffer.
Private Member Functions
bool isResponseComplete (const std::string &buffer) const
Check if response is complete.
Static Private Member Functions
static bool endsWithPrompt (const std::string &buffer)
Check if buffer ends with a command prompt.
Private Attributes
asio::io_context io_
Boost.Asio I/O context for async operations.
tcp::socket socket_
TCP socket for Telnet communication.
bool connected_
Current connection state.
bool last_io_ok_
Result of last I/O operation (for FSM guards)
std::string last_response_
Buffer containing last received response.
std::chrono::milliseconds io_timeout_
Overall I/O timeout for commands.
Detailed Description
TCP/Telnet client for substation relay communication.
Provides a complete Telnet client implementation using Boost.Asio for asynchronous networking. Key features:
Connection Management: Timeout-based connection with automatic cleanup
Command/Response: Send commands and receive responses with prompt detection
State Tracking: Maintains connection state and last I/O result for FSM guards
Non-blocking I/O: Uses idle timeout detection for SER data collection
Internal State Diagram
Invariant
socket_ is valid throughout object lifetime
connected_ reflects actual socket connection state
Definition at line 131 of file client.hpp.
Constructor & Destructor Documentation
TelnetClient()
TelnetClient::TelnetClient ()
Construct a new TelnetClient object.
Initializes the Boost.Asio I/O context and TCP socket. Sets default I/O timeout to 5000ms. Socket starts in disconnected state.
Postcondition
connected_ == false
last_io_ok_ == false
io_timeout_ == 5000ms
Definition at line 40 of file client.cpp.
References connected_, io_, io_timeout_, last_io_ok_, and socket_.
Member Function Documentation
clearLastResponse()
void TelnetClient::clearLastResponse ()
Clear the last response buffer.
Called before each new command to reset state.
Postcondition
last_response_.empty() == true
Definition at line 226 of file client.cpp.
References last_response_.
Referenced by ConnectAction::operator()(), Login1Action::operator()(), and PollSerAction::operator()().
connectCheck()
bool TelnetClient::connectCheck (const std::string & host, int port, std::chrono::milliseconds timeout)
Connect to a Telnet server with timeout.
Establishes TCP connection to the specified host and port. Uses asynchronous connect with timer for timeout handling.
Connection Process:
Resolve hostname to IP addresses
Start async connect with timeout timer
Run I/O context until connection or timeout
Update connection state
Parameters
host Target hostname or IP address
port Target port number (typically 23 for Telnet)
timeout Maximum time to wait for connection
Returns
true Connection established successfully
false Connection failed (timeout, refused, or error)
Precondition
Socket may be in any state (will be closed and reopened)
Postcondition
connected_ reflects connection result
last_io_ok_ reflects connection result
Exceptions
None (catches all exceptions internally)
See also
isConnected() Check connection state after connect
Definition at line 46 of file client.cpp.
References connected_, io_, last_io_ok_, and socket_.
Referenced by ConnectAction::operator()().
endsWithPrompt()
bool TelnetClient::endsWithPrompt (const std::string & buffer) static private
Check if buffer ends with a command prompt.
Searches last 50 characters for prompt patterns:
"=>" (relay prompt)
"> ", "# ", "$ " (Unix-style prompts)
"? " (question prompts)
Parameters
buffer Response buffer to check
Returns
true Prompt detected at end
false No prompt found
Definition at line 261 of file client.cpp.
Referenced by isResponseComplete().
getLastIoResult()
bool TelnetClient::getLastIoResult () const
Get the result of the last I/O operation.
Used by FSM guards to check operation success.
Returns
true Last operation succeeded
false Last operation failed
Definition at line 221 of file client.cpp.
References last_io_ok_.
Referenced by ConnectFailGuard::operator()(), ConnectOkGuard::operator()(), Login1CompleteGuard::operator()(), and SerCompleteGuard::operator()().
getLastResponse()
const std::string & TelnetClient::getLastResponse () const
Get the last response received.
Returns
const std::string& Reference to last response buffer
Definition at line 216 of file client.cpp.
References last_response_.
Referenced by InvalidLoginGuard::operator()(), Login1CompleteGuard::operator()(), and SerCompleteGuard::operator()().
isConnected()
bool TelnetClient::isConnected () const
Check if client is currently connected.
Returns
true Socket is connected
false Socket is disconnected
Definition at line 210 of file client.cpp.
References connected_.
isResponseComplete()
bool TelnetClient::isResponseComplete (const std::string & buffer) const private
Check if response is complete.
Detects response completion by:
Finding "SER Response Complete" marker
Detecting command prompt at buffer end
Parameters
buffer Response buffer to check
Returns
true Response is complete
false Still waiting for more data
Definition at line 251 of file client.cpp.
References endsWithPrompt().
Referenced by SendCmdReceiveData().
LoginLevel1Function()
bool TelnetClient::LoginLevel1Function (const std::string & username, const std::string & password)
Perform Level 1 login authentication.
Sends username and password as sequential commands. Used for basic authentication to substation relay devices.
Login Sequence:
Client: username\r\n
Server: Password: (or prompt)
Client: password\r\n
Server: command prompt (e.g., ">")
Parameters
username Level 1 username
password Level 1 password
Returns
true Both username and password accepted
false Authentication failed at any step
See also
Login1CompleteGuard FSM guard for checking login success
Definition at line 232 of file client.cpp.
References SendCmdReceiveData().
Referenced by Login1Action::operator()().
SendCmdReceiveData()
bool TelnetClient::SendCmdReceiveData (const std::string & cmd, std::string & outBuffer)
Send command and receive response data.
Generic command/response method used by Boost.SML actions. Sends command with CRLF termination and collects response using non-blocking I/O with idle timeout detection.
Response Collection Algorithm
1. Send command + "\r\n"
2. Set socket to non-blocking mode
3. Loop:
   a. Try read from socket
   b. If would_block: check idle timeout
   c. If data received: update idle timer, append to buffer
   d. Check for response completion (prompt or marker)
   e. Check overall timeout
4. Return buffer contents
Parameters
[in] cmd Command string to send (without CRLF)
[out] outBuffer Buffer to receive response data
Returns
true Command sent and response received successfully
false Not connected, write error, or timeout with no data
Precondition
isConnected() == true
Postcondition
outBuffer contains response data
last_response_ updated with response
last_io_ok_ reflects operation result
Note
SER command uses longer idle timeout (500ms vs 200ms)
Definition at line 105 of file client.cpp.
References connected_, io_timeout_, isResponseComplete(), last_io_ok_, last_response_, and socket_.
Referenced by LoginLevel1Function(), and PollSerAction::operator()().
Member Data Documentation
connected_
bool TelnetClient::connected_ private
Current connection state.
Definition at line 314 of file client.hpp.
Referenced by connectCheck(), isConnected(), SendCmdReceiveData(), and TelnetClient().
io_
asio::io_context TelnetClient::io_ private
Boost.Asio I/O context for async operations.
Definition at line 312 of file client.hpp.
Referenced by connectCheck(), and TelnetClient().
io_timeout_
std::chrono::milliseconds TelnetClient::io_timeout_ private
Overall I/O timeout for commands.
Definition at line 317 of file client.hpp.
Referenced by SendCmdReceiveData(), and TelnetClient().
last_io_ok_
bool TelnetClient::last_io_ok_ private
Result of last I/O operation (for FSM guards)
Definition at line 315 of file client.hpp.
Referenced by connectCheck(), getLastIoResult(), SendCmdReceiveData(), and TelnetClient().
last_response_
std::string TelnetClient::last_response_ private
Buffer containing last received response.
Definition at line 316 of file client.hpp.
Referenced by clearLastResponse(), getLastResponse(), and SendCmdReceiveData().
socket_
tcp::socket TelnetClient::socket_ private
TCP socket for Telnet communication.
Definition at line 313 of file client.hpp.
Referenced by connectCheck(), SendCmdReceiveData(), and TelnetClient().
The documentation for this class was generated from the following files:
client.hpp
client.cpp