Telnet-SML: TimeSyncManager Class Reference
TimeSyncManager Class Reference
High-level orchestrator for DATE synchronization.
#include <time_sync_manager.hpp>
Public Member Functions
TimeSyncManager (RelayService &relay)
Construct with a RelayService instance.
std::string handleAction (const std::string &action)
Process a JSON action string from WebSocket and return a JSON response.
Static Public Member Functions
static std::string getLocalPCTime ()
Get current local PC time formatted as "YYYY-MM-DD HH:MM:SS".
static std::pair< std::string, int64_t > compareTime (const std::string &relayTime, const std::string &pcTime)
Compare relay time and PC time.
Private Member Functions
std::string handleReadTime ()
std::string handleSyncTime ()
Static Private Member Functions
static std::chrono::system_clock::time_point parseToTimePoint (const std::string &dt)
Parse "YYYY-MM-DD HH:MM:SS" to system_clock::time_point.
static std::string escapeJson (const std::string &s)
static std::string buildErrorJson (const std::string &action, const std::string &msg)
Private Attributes
RelayService & relay_
Detailed Description
High-level orchestrator for DATE synchronization.
Thread-safety: each public method acquires RelayService's internal mutex through the RelayService calls, so this class itself is safe to call from any thread (e.g. posted on a Boost.Asio strand).
Definition at line 67 of file time_sync_manager.hpp.
Constructor & Destructor Documentation
TimeSyncManager()
TimeSyncManager::TimeSyncManager (RelayService & relay) inline explicit
Construct with a RelayService instance.
Parameters
relay RelayService wrapping TelnetClient (must outlive this manager)
Definition at line 75 of file time_sync_manager.hpp.
References relay_.
Member Function Documentation
buildErrorJson()
std::string TimeSyncManager::buildErrorJson (const std::string & action, const std::string & msg) inline static private
Definition at line 247 of file time_sync_manager.hpp.
References escapeJson().
Referenced by handleAction(), and handleSyncTime().
compareTime()
std::pair< std::string, int64_t > TimeSyncManager::compareTime (const std::string & relayTime, const std::string & pcTime) inline static
Compare relay time and PC time.
Parameters
relayTime Datetime string from relay
pcTime Datetime string from local PC
Returns
Pair of { status, diff_seconds }. status = "in_sync" if |diff| <= 1 s, otherwise "out_of_sync".
Definition at line 115 of file time_sync_manager.hpp.
References parseToTimePoint().
Referenced by handleReadTime().
escapeJson()
std::string TimeSyncManager::escapeJson (const std::string & s) inline static private
Definition at line 232 of file time_sync_manager.hpp.
getLocalPCTime()
std::string TimeSyncManager::getLocalPCTime () inline static
Get current local PC time formatted as "YYYY-MM-DD HH:MM:SS".
Returns
Formatted datetime string with second-level precision
Definition at line 87 of file time_sync_manager.hpp.
Referenced by handleReadTime(), and handleSyncTime().
handleAction()
std::string TimeSyncManager::handleAction (const std::string & action) inline
Process a JSON action string from WebSocket and return a JSON response.
Supported actions:
"read_time" → reads relay time, gets PC time, compares
"sync_time" → writes PC time to relay
Parameters
action The "action" field value from the incoming JSON
Returns
JSON response string to send back via WebSocket
Definition at line 140 of file time_sync_manager.hpp.
References buildErrorJson(), handleReadTime(), and handleSyncTime().
handleReadTime()
std::string TimeSyncManager::handleReadTime () inline private
Definition at line 153 of file time_sync_manager.hpp.
References compareTime(), escapeJson(), getLocalPCTime(), and relay_.
Referenced by handleAction().
handleSyncTime()
std::string TimeSyncManager::handleSyncTime () inline private
Definition at line 187 of file time_sync_manager.hpp.
References buildErrorJson(), escapeJson(), getLocalPCTime(), and relay_.
Referenced by handleAction().
parseToTimePoint()
std::chrono::system_clock::time_point TimeSyncManager::parseToTimePoint (const std::string & dt) inline static private
Parse "YYYY-MM-DD HH:MM:SS" to system_clock::time_point.
Definition at line 213 of file time_sync_manager.hpp.
Referenced by compareTime().
Member Data Documentation
relay_
RelayService& TimeSyncManager::relay_ private
Definition at line 258 of file time_sync_manager.hpp.
Referenced by handleReadTime(), handleSyncTime(), and TimeSyncManager().
The documentation for this class was generated from the following file:
time_sync_manager.hpp