Telnet-SML: RelayService Class Reference
RelayService Class Reference
Thread-safe wrapper around TelnetClient for DATE operations.
#include <relay_service.hpp>
Classes
struct DateResult
Result of a relay DATE operation.
struct CommandResult
Result of a generic relay command.
Public Member Functions
RelayService (TelnetClient &client)
Construct with external TelnetClient reference.
DateResult readRelayTime ()
Send DATE read command and decode ASN.1 response.
DateResult syncRelayTime (const std::string &datetime)
Send SETTIME command with the given datetime to the relay.
CommandResult sendRelayCommand (const std::string &cmd)
Send an arbitrary command to the relay and check for ACK.
Static Private Member Functions
static std::string cleanRelayText (const std::string &raw)
Strip Telnet echo/prompts from raw response, return trimmed datetime.
Private Attributes
TelnetClient & client_
std::mutex mutex_
Detailed Description
Thread-safe wrapper around TelnetClient for DATE operations.
All public methods lock the internal mutex so that the ReceptionWorker's command queue and the TimeSyncManager can share the same underlying TelnetClient safely (only one caller at a time sends Telnet I/O).
Usage (inside ReceptionWorker or ProcessingWorker)
RelayService relay(client);
auto [ok, dt] = relay.readRelayTime();
if (ok)
    std::cout << "Relay time: " << dt << "\n";
Definition at line 132 of file relay_service.hpp.
Constructor & Destructor Documentation
RelayService()
RelayService::RelayService (TelnetClient & client) inline explicit
Construct with external TelnetClient reference.
The caller retains ownership; the client must outlive the service.
Definition at line 150 of file relay_service.hpp.
References client_.
Member Function Documentation
cleanRelayText()
std::string RelayService::cleanRelayText (const std::string & raw) inline static private
Strip Telnet echo/prompts from raw response, return trimmed datetime.
Definition at line 325 of file relay_service.hpp.
Referenced by readRelayTime().
readRelayTime()
DateResult RelayService::readRelayTime () inline
Send DATE read command and decode ASN.1 response.
Returns
DateResult with success flag and decoded datetime
Definition at line 162 of file relay_service.hpp.
References cleanRelayText(), client_, RelayService::DateResult::datetime, asn_date::decodeASN1Date(), RelayService::DateResult::error, mutex_, and RelayService::DateResult::success.
sendRelayCommand()
CommandResult RelayService::sendRelayCommand (const std::string & cmd) inline
Send an arbitrary command to the relay and check for ACK.
Parameters
cmd Command string to send (e.g. "PAS LEVEL1 TAIL1")
Returns
CommandResult with success flag, raw response, and optional error
Definition at line 281 of file relay_service.hpp.
References client_, RelayService::CommandResult::error, mutex_, RelayService::CommandResult::response, and RelayService::CommandResult::success.
syncRelayTime()
DateResult RelayService::syncRelayTime (const std::string & datetime) inline
Send SETTIME command with the given datetime to the relay.
Parameters
datetime Formatted string: "YYYY-MM-DD HH:MM:SS"
Returns
DateResult with success/failure and any error message
Definition at line 218 of file relay_service.hpp.
References client_, RelayService::DateResult::datetime, asn_date::encodeASN1Date(), RelayService::DateResult::error, mutex_, and RelayService::DateResult::success.
Member Data Documentation
client_
TelnetClient& RelayService::client_ private
Definition at line 359 of file relay_service.hpp.
Referenced by readRelayTime(), RelayService(), sendRelayCommand(), and syncRelayTime().
mutex_
std::mutex RelayService::mutex_ private
Definition at line 360 of file relay_service.hpp.
Referenced by readRelayTime(), sendRelayCommand(), and syncRelayTime().
The documentation for this class was generated from the following file:
relay_service.hpp