Telnet-SML: TelnetServer Class Reference
TelnetServer Class Reference
Basic Telnet Server for Substation Monitoring.
Public Member Functions
TelnetServer (int port)
void start ()
void stop ()
Private Member Functions
void handleClient (tcp::socket &socket)
std::string processCommand (const std::string &command)
Private Attributes
boost::asio::io_context io_
tcp::acceptor acceptor_
bool running_
Detailed Description
Basic Telnet Server for Substation Monitoring.
Implements a simple telnet server that:
Accepts TCP connections on a specified port
Presents an interactive command prompt
Processes substation monitoring commands
Returns formatted responses
Handles disconnection gracefully
The server operates in synchronous mode:
Blocks on accept() waiting for connections
Handles one client completely before accepting next
Uses blocking I/O for command/response
No concurrent client support
Server Lifecycle:
Constructor: Initialize acceptor on port
start(): Enter accept loop
handleClient(): Process commands for connected client
processCommand(): Generate responses
Client disconnects, return to step 2
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 107 of file server.cpp.
Constructor & Destructor Documentation
TelnetServer()
TelnetServer::TelnetServer (int port) inline
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 141 of file server.cpp.
References acceptor_, io_, and running_.
Member Function Documentation
handleClient()
void TelnetServer::handleClient (tcp::socket & socket) inline private
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 318 of file server.cpp.
References processCommand().
Referenced by start().
processCommand()
std::string TelnetServer::processCommand (const std::string & command) inline private
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 451 of file server.cpp.
Referenced by handleClient().
start()
void TelnetServer::start () inline
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 192 of file server.cpp.
References acceptor_, handleClient(), io_, and running_.
Referenced by main().
stop()
void TelnetServer::stop () inline
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 257 of file server.cpp.
References running_.
Member Data Documentation
acceptor_
tcp::acceptor TelnetServer::acceptor_ private
TCP acceptor for incoming connections
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 111 of file server.cpp.
Referenced by start(), and TelnetServer().
io_
boost::asio::io_context TelnetServer::io_ private
Boost.Asio I/O context for socket operations
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 110 of file server.cpp.
Referenced by start(), and TelnetServer().
running_
bool TelnetServer::running_ private
Server running flag (false to stop)
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 112 of file server.cpp.
Referenced by start(), stop(), and TelnetServer().
The documentation for this class was generated from the following file:
server.cpp