Telnet-SML: PasswordManager Class Reference
PasswordManager Class Reference
Validates and executes relay password changes (LEVEL1 / LEVEL2).
#include <password_manager.hpp>
Classes
struct PasswordResult
Result of a password change operation.
Public Member Functions
PasswordManager (RelayService &relay)
Construct with a RelayService instance.
PasswordResult changePassword (const std::string &level, const std::string &value)
Change relay password for specified access level.
std::string handleAction (const std::string &jsonMsg)
Process a full JSON message for the "change_password" action.
Static Public Member Functions
static bool validatePassword (const std::string &value)
Validate that a password value is in the allowed set.
static bool validateLevel (const std::string &level)
Validate that a level string is valid.
Static Private Member Functions
static std::string extractJsonField (const std::string &json, const std::string &fieldName)
Extract a string field value from a simple JSON object.
static std::string escapeJson (const std::string &s)
static std::string buildSuccessJson ()
static std::string buildErrorJson (const std::string &msg)
Private Attributes
RelayService & relay_
Thread-safe relay communication service.
Detailed Description
Validates and executes relay password changes (LEVEL1 / LEVEL2).
Provides a high-level interface for:
Validating password values against the allowed set (TAIL1 / OTTER1)
Building ASN.1 Tag 34 encoded payloads
Sending password change commands to the relay
Handling WebSocket JSON requests end-to-end
Thread-safety: each public method acquires RelayService's internal mutex through the RelayService calls, so this class itself is safe to call from any thread (e.g. posted on a Boost.Asio strand).
WebSocket Protocol
Request:
{
  "action": "change_password",
  "level": "LEVEL1",
  "value": "TAIL1"
}
Success Response:
{ "action": "change_password", "status": "success" }
Failure Response:
{ "action": "change_password", "status": "failed", "error": "..." }
Definition at line 157 of file password_manager.hpp.
Constructor & Destructor Documentation
PasswordManager()
PasswordManager::PasswordManager (RelayService & relay) inline explicit
Construct with a RelayService instance.
Parameters
relay RelayService wrapping TelnetClient (must outlive this manager)
Definition at line 174 of file password_manager.hpp.
References relay_.
Member Function Documentation
buildErrorJson()
std::string PasswordManager::buildErrorJson (const std::string & msg) inline static private
Definition at line 347 of file password_manager.hpp.
References escapeJson().
Referenced by handleAction().
buildSuccessJson()
std::string PasswordManager::buildSuccessJson () inline static private
Definition at line 342 of file password_manager.hpp.
Referenced by handleAction().
changePassword()
PasswordResult PasswordManager::changePassword (const std::string & level, const std::string & value) inline
Change relay password for specified access level.
Validates inputs, builds ASN.1 Tag 34 payload, sends the password change command to the relay, and waits for ACK. Plain password values are never written to logs.
Parameters
level "LEVEL1" or "LEVEL2"
value "TAIL1" or "OTTER1"
Returns
PasswordResult with success flag and optional error
Definition at line 218 of file password_manager.hpp.
References asn_password::encodeASN1Password(), PasswordManager::PasswordResult::error, relay_, PasswordManager::PasswordResult::success, validateLevel(), and validatePassword().
Referenced by handleAction().
escapeJson()
std::string PasswordManager::escapeJson (const std::string & s) inline static private
Definition at line 327 of file password_manager.hpp.
extractJsonField()
std::string PasswordManager::extractJsonField (const std::string & json, const std::string & fieldName) inline static private
Extract a string field value from a simple JSON object.
Parameters
json Raw JSON string
fieldName Field name to extract (without quotes)
Returns
Extracted value string, or empty on failure
Definition at line 313 of file password_manager.hpp.
Referenced by handleAction().
handleAction()
std::string PasswordManager::handleAction (const std::string & jsonMsg) inline
Process a full JSON message for the "change_password" action.
Extracts "level" and "value" from the JSON, validates, executes the password change, and returns a JSON response. Password values are never logged.
Parameters
jsonMsg Full JSON message string from WebSocket
Returns
JSON response string to send back via WebSocket
Definition at line 273 of file password_manager.hpp.
References buildErrorJson(), buildSuccessJson(), changePassword(), extractJsonField(), validateLevel(), and validatePassword().
validateLevel()
bool PasswordManager::validateLevel (const std::string & level) inline static
Validate that a level string is valid.
Parameters
level Level string to validate
Returns
true if level is "LEVEL1" or "LEVEL2"
Definition at line 200 of file password_manager.hpp.
Referenced by changePassword(), and handleAction().
validatePassword()
bool PasswordManager::validatePassword (const std::string & value) inline static
Validate that a password value is in the allowed set.
Only "TAIL1" and "OTTER1" are permitted.
Parameters
value Password string to validate
Returns
true if value is allowed
Definition at line 189 of file password_manager.hpp.
Referenced by changePassword(), and handleAction().
Member Data Documentation
relay_
RelayService& PasswordManager::relay_ private
Thread-safe relay communication service.
Definition at line 358 of file password_manager.hpp.
Referenced by changePassword(), and PasswordManager().
The documentation for this class was generated from the following file:
password_manager.hpp