Telnet-SML: dll_example.cpp File Reference
dll_example.cpp File Reference
Example Application Using Telnet-SML DLL.
#include <iostream>
#include "telnet_sml_app.hpp"
Functions
int main ()
Example application entry point.
Detailed Description
Example Application Using Telnet-SML DLL.
Demonstrates how to use the telnet_sml.dll library in an external application. This example connects to a relay, retrieves SER data, and displays it through the WebSocket server.
Building This Example
# First build the DLL
./build_dll.ps1
# Then compile this example
g++ -std=c++17 ^
    -I third_party/sml/include ^
    -I C:\Libraries\boost_1_90_0 ^
    -I C:\sqlite ^
    dll_example.cpp ^
    -Llib -ltelnet_sml ^
    -lws2_32 -lmswsock ^
    -o dll_example.exe
# Copy DLL to executable location
copy lib\telnet_sml.dll .
# Run
./dll_example.exe
Author
Telnet-SML Development Team
Version
1.0.0
Date
2026
Definition in file dll_example.cpp.
Function Documentation
main()
int main ()
Example application entry point.
Demonstrates the DLL facade workflow:
Create TelnetSmlApp
Start the application
Wait for exit signal
Examples
C:/Users/qures/OneDrive/Desktop/Work/Telnet-App/Older/Telnet-SML/server.cpp.
Definition at line 50 of file dll_example.cpp.
References TelnetSmlApp::start(), TelnetSmlApp::stop(), and TelnetSmlApp::waitForExit().