Telnet-SML: asn_tlv Namespace Reference
asn_tlv Namespace Reference
ASN.1 BER/TLV encoding and decoding utilities.
Classes
struct TlvInfo
Parsed TLV header information.
Functions
bool readLength (const uint8_t *buffer, std::size_t size, std::size_t offset, std::size_t &length, std::size_t &nextOffset, std::string *error)
Read BER length encoding from a buffer.
bool readTlv (const uint8_t *buffer, std::size_t size, std::size_t offset, TlvInfo &info, std::string *error)
Read and parse a complete TLV structure.
void berAppendLength (std::vector< uint8_t > &out, std::size_t len)
Append BER length encoding to an output buffer.
void berAppendTlv (std::vector< uint8_t > &out, uint8_t tag, const uint8_t *value, std::size_t len)
Append a complete TLV structure to an output buffer.
void berAppendString (std::vector< uint8_t > &out, uint8_t tag, const std::string &value)
Append a string as a TLV structure.
std::vector< uint8_t > encodeSerRecordsToTlv (const std::vector< SERRecord > &records)
Encode SER records to ASN.1 BER/TLV format.
bool decodeSerRecordsFromTlv (const uint8_t *data, std::size_t size, std::vector< SERRecord > &out, std::string *error=nullptr)
Decode ASN.1 BER/TLV payload to SER records.
Detailed Description
ASN.1 BER/TLV encoding and decoding utilities.
Function Documentation
berAppendLength()
void asn_tlv::berAppendLength (std::vector< uint8_t > & out, std::size_t len) inline
Append BER length encoding to an output buffer.
Uses short form for lengths < 128, long form otherwise.
Parameters
[out] out Output buffer to append to
len Length value to encode
Definition at line 219 of file asn_tlv_codec.hpp.
Referenced by berAppendTlv().
berAppendString()
void asn_tlv::berAppendString (std::vector< uint8_t > & out, uint8_t tag, const std::string & value) inline
Append a string as a TLV structure.
Parameters
[out] out Output buffer to append to
tag Tag byte
value String value to encode
Definition at line 270 of file asn_tlv_codec.hpp.
References berAppendTlv().
Referenced by encodeSerRecordsToTlv().
berAppendTlv()
void asn_tlv::berAppendTlv (std::vector< uint8_t > & out, uint8_t tag, const uint8_t * value, std::size_t len) inline
Append a complete TLV structure to an output buffer.
Parameters
[out] out Output buffer to append to
tag Tag byte
value Pointer to value bytes (may be nullptr if len is 0)
len Length of value
Definition at line 253 of file asn_tlv_codec.hpp.
References berAppendLength().
Referenced by berAppendString(), and encodeSerRecordsToTlv().
decodeSerRecordsFromTlv()
bool asn_tlv::decodeSerRecordsFromTlv (const uint8_t * data, std::size_t size, std::vector< SERRecord > & out, std::string * error = nullptr) inline
Decode ASN.1 BER/TLV payload to SER records.
Parses a top-level APPLICATION 1 TLV and extracts all SEQUENCE TLVs containing record data.
Parameters
data Input buffer containing TLV payload
size Size of input buffer in bytes
[out] out Vector to receive decoded records
[out] error Optional pointer to receive error message
Returns
true if all records were decoded successfully
false on parse error (details in error if provided)
Note
Output vector is cleared before decoding
Definition at line 336 of file asn_tlv_codec.hpp.
References SERRecord::description, asn_tlv::TlvInfo::length, asn_tlv::TlvInfo::nextOffset, readTlv(), SERRecord::record_id, SERRecord::status, asn_tlv::TlvInfo::tag, SERRecord::timestamp, and asn_tlv::TlvInfo::valueStart.
Referenced by SharedSerReader::runLoop().
encodeSerRecordsToTlv()
std::vector< uint8_t > asn_tlv::encodeSerRecordsToTlv (const std::vector< SERRecord > & records) inline
Encode SER records to ASN.1 BER/TLV format.
Creates a top-level APPLICATION 1 TLV containing zero or more SEQUENCE TLVs, each with context-specific fields for record data.
Output Structure
0x61 [len] {
  0x30 [len] {
    0x80 [len] record_id
    0x81 [len] timestamp
    0x82 [len] status
    0x83 [len] description
  }
  ... (more records)
}
Parameters
records Vector of SERRecord to encode
Returns
std::vector<uint8_t> Binary TLV payload
Definition at line 297 of file asn_tlv_codec.hpp.
References berAppendString(), and berAppendTlv().
Referenced by SERWebSocketServer::broadcast(), PollSerAction::operator()(), and WebSocketSession::sendData().
readLength()
bool asn_tlv::readLength (const uint8_t * buffer, std::size_t size, std::size_t offset, std::size_t & length, std::size_t & nextOffset, std::string * error) inline
Read BER length encoding from a buffer.
Handles both short form (single byte < 128) and long form (first byte indicates count of following length bytes).
Parameters
buffer Input buffer
size Buffer size in bytes
offset Current position in buffer
[out] length Decoded length value
[out] nextOffset Position after length bytes
[out] error Optional error message on failure
Returns
true if decoding succeeded
false if encoding is invalid or out of range
Definition at line 129 of file asn_tlv_codec.hpp.
Referenced by readTlv().
readTlv()
bool asn_tlv::readTlv (const uint8_t * buffer, std::size_t size, std::size_t offset, TlvInfo & info, std::string * error) inline
Read and parse a complete TLV structure.
Extracts tag, length, and value boundaries from buffer.
Parameters
buffer Input buffer
size Buffer size in bytes
offset Current position in buffer
[out] info Parsed TLV information
[out] error Optional error message on failure
Returns
true if parsing succeeded
false if the TLV is invalid or out of range
Definition at line 180 of file asn_tlv_codec.hpp.
References asn_tlv::TlvInfo::constructed, asn_tlv::TlvInfo::length, asn_tlv::TlvInfo::nextOffset, readLength(), asn_tlv::TlvInfo::tag, and asn_tlv::TlvInfo::valueStart.
Referenced by decodeSerRecordsFromTlv().