Telnet-SML: asn_password Namespace Reference
asn_password Namespace Reference
Functions
std::vector< uint8_t > encodeASN1Password (const std::string &password)
Encode a password string as ASN.1 BER TLV with Tag 34.
bool decodeASN1Password (const uint8_t *data, std::size_t size, std::string &password, std::string *error=nullptr)
Decode an ASN.1 BER TLV payload with Tag 34 to a password string.
Function Documentation
decodeASN1Password()
bool asn_password::decodeASN1Password (const uint8_t * data, std::size_t size, std::string & password, std::string * error = nullptr) inline
Decode an ASN.1 BER TLV payload with Tag 34 to a password string.
Parameters
data Raw BER bytes
size Number of bytes
[out] password Decoded password string
[out] error Optional error message on failure
Returns
true on success
Definition at line 91 of file password_manager.hpp.
References ASN1_PASSWORD_TAG, asn_tlv::TlvInfo::length, asn_tlv::readTlv(), asn_tlv::TlvInfo::tag, and asn_tlv::TlvInfo::valueStart.
encodeASN1Password()
std::vector< uint8_t > asn_password::encodeASN1Password (const std::string & password) inline
Encode a password string as ASN.1 BER TLV with Tag 34.
Parameters
password Password string to encode
Returns
std::vector<uint8_t> BER-encoded TLV payload
Definition at line 74 of file password_manager.hpp.
References ASN1_PASSWORD_TAG, and asn_tlv::berAppendString().
Referenced by PasswordManager::changePassword().