Telnet-SML: asn_date Namespace Reference
asn_date Namespace Reference
Functions
std::vector< uint8_t > encodeASN1Date (const std::string &datetime)
Encode a datetime string as ASN.1 BER TLV with Tag 33.
bool decodeASN1Date (const uint8_t *data, std::size_t size, std::string &datetime, std::string *error=nullptr)
Decode an ASN.1 BER TLV payload with Tag 33 to a datetime string.
Function Documentation
decodeASN1Date()
bool asn_date::decodeASN1Date (const uint8_t * data, std::size_t size, std::string & datetime, std::string * error = nullptr) inline
Decode an ASN.1 BER TLV payload with Tag 33 to a datetime string.
Parameters
data Raw BER bytes
size Number of bytes
[out] datetime Decoded datetime string
[out] error Optional error message on failure
Returns
true on success
Definition at line 84 of file relay_service.hpp.
References ASN1_DATE_TAG, asn_tlv::TlvInfo::length, asn_tlv::readTlv(), asn_tlv::TlvInfo::tag, and asn_tlv::TlvInfo::valueStart.
Referenced by RelayService::readRelayTime().
encodeASN1Date()
std::vector< uint8_t > asn_date::encodeASN1Date (const std::string & datetime) inline
Encode a datetime string as ASN.1 BER TLV with Tag 33.
Parameters
datetime Formatted string: "YYYY-MM-DD HH:MM:SS"
Returns
std::vector<uint8_t> BER-encoded TLV payload
Definition at line 67 of file relay_service.hpp.
References ASN1_DATE_TAG, and asn_tlv::berAppendString().
Referenced by RelayService::syncRelayTime().