Telnet-SML: ser_json_writer.hpp File Reference
ser_json_writer.hpp File Reference
JSON serialization and file output for SER records.
#include <fstream>
#include <string>
#include <vector>
#include "ser_record.hpp"
Functions
std::string escapeJson (const std::string &value)
Escape special characters for JSON string values.
std::string recordsToJsonTable (const std::vector< SERRecord > &records)
Convert SER records to a JSON array string.
bool writeJsonToFile (const std::string &path, const std::string &json, std::string *error=nullptr)
Write JSON string to a file.
Detailed Description
JSON serialization and file output for SER records.
Utility functions for converting SER records to JSON and writing the result to a file for web UI consumption.
Output Format
Generates a JSON array compatible with Tabulator.js:
[
  {
    "sno": 45,
    "date": "02/14/22",
    "time": "12:47:19.970",
    "element": "SALARM",
    "state": "Asserted"
  },
  ...
]
Data Flow
See also
SharedSerReader Consumer that uses these functions
SERRecord Input data structure
Author
Telnet-SML Development Team
Version
1.0.0
Date
2026
Definition in file ser_json_writer.hpp.
Function Documentation
escapeJson()
std::string escapeJson (const std::string & value) inline
Escape special characters for JSON string values.
Escapes double quotes and backslashes to ensure valid JSON output.
Parameters
value Input string to escape
Returns
std::string Escaped string safe for JSON embedding
Definition at line 70 of file ser_json_writer.hpp.
Referenced by recordsToJsonTable().
recordsToJsonTable()
std::string recordsToJsonTable (const std::vector< SERRecord > & records) inline
Convert SER records to a JSON array string.
Formats records as JSON array with fields:
sno: Record ID (numeric if parseable, string otherwise)
date: Date portion of timestamp (before space)
time: Time portion of timestamp (after space)
element: Description field
state: Status field
Parameters
records Vector of SERRecord to convert
Returns
std::string JSON array string
Note
Timestamp is automatically split into date and time
All string values are JSON-escaped
Definition at line 101 of file ser_json_writer.hpp.
References escapeJson().
Referenced by SharedSerReader::runLoop().
writeJsonToFile()
bool writeJsonToFile (const std::string & path, const std::string & json, std::string * error = nullptr) inline
Write JSON string to a file.
Opens file in binary mode with truncation and writes JSON content.
Parameters
path Output file path
json JSON string to write
[out] error Optional pointer to receive error message
Returns
true if the file was written successfully
false if the write failed (error message in error if provided)
Note
Opens file with std::ios::binary to preserve line endings
Truncates existing file content
Definition at line 161 of file ser_json_writer.hpp.
Referenced by SharedSerReader::runLoop().