Telnet-SML: ser_record.hpp File Reference
ser_record.hpp File Reference
System Event Record (SER) data structure and parser.
#include "dll_export.hpp"
#include <string>
#include <vector>
#include <sstream>
#include <algorithm>
#include <cctype>
Classes
struct SERRecord
Structure representing a System Event Record (SER).
Functions
std::string sanitizeSerLine (const std::string &line)
Parse SER response string into a vector of SERRecord.
std::vector< SERRecord > parseSERResponse (const std::string &response)
Parse a raw SER command response into a vector of SERRecord.
Detailed Description
System Event Record (SER) data structure and parser.
Defines the SERRecord structure and a parser that converts raw Telnet SER responses into structured records.
SER Record Format
Substation relays output SER data in the following format:
#      Date      Time           Element           State
    45 02/14/22  12:47:19.970   Power loss
    43 12/30/25  15:49:30.860   SALARM            Asserted
    42 12/30/25  15:49:30.850   VMIN              Deasserted
Data Flow
Usage Example
std::string response = "45 02/14/22 12:47:19.970 Power loss\n";
auto records = parseSERResponse(response);
for (const auto& rec : records) {
    std::cout << rec.record_id << ": " << rec.description << "\n";
}
See also
SERDatabase Database storage for SER records
PollSerAction FSM action that uses the parser
Author
Telnet-SML Development Team
Version
1.0.0
Date
2026
Definition in file ser_record.hpp.
Function Documentation
parseSERResponse()
std::vector< SERRecord > parseSERResponse (const std::string & response) inline
Parse a raw SER command response into a vector of SERRecord.
Splits the response into lines, sanitises each one via sanitizeSerLine(), then extracts the record number, date, time, element name, and optional state ("Asserted" / "Deasserted"). Header lines (starting with '#' or containing "Date") and blank lines are silently skipped.
Parsing Rules
Lines starting with '#' are skipped (header).
Lines containing "Date" are skipped (column header).
A valid record line must begin with a digit.
Date format is validated as MM/DD/YY (slashes at positions 2 and 5).
Time must contain at least one colon.
The last word is extracted as state if it equals "Asserted" or "Deasserted"; otherwise the entire tail is the element name.
Parameters
response Raw text response from the SER command.
Returns
std::vector<SERRecord> Parsed records (may be empty if no valid records are found).
Note
relay_id and relay_name are left empty; the caller (pipeline) is responsible for filling them in.
See also
sanitizeSerLine() Pre-processing step for each line
SERRecord The structure returned for each parsed event
SERDatabase::insertRecords() For storing the results
Definition at line 293 of file ser_record.hpp.
References SERRecord::description, SERRecord::record_id, sanitizeSerLine(), SERRecord::status, and SERRecord::timestamp.
Referenced by PollSerAction::operator()(), and PipelineProcessingWorker::runLoop().
sanitizeSerLine()
std::string sanitizeSerLine (const std::string & line) inline
Parse SER response string into a vector of SERRecord.
Parses raw text response from the SER command into structured records. Handles the specific format output by substation relay devices.
Input Format
#      Date      Time           Element           State
    45 02/14/22  12:47:19.970   Power loss
    43 12/30/25  15:49:30.860   SALARM            Asserted
Parsing Algorithm
Parsing Rules
Lines starting with '#' are skipped (header)
Lines containing "Date" are skipped (column headers)
Lines must start with a number (record #)
State detection: "Asserted" or "Deasserted" at end
Whitespace is trimmed from all fields
Parameters
response Raw text response from the SER command
Returns
std::vector<SERRecord> Parsed records (may be empty if parsing fails)
Note
Date format is preserved from relay (MM/DD/YY)
Empty lines and non-record lines are silently skipped
See also
SERRecord Structure for individual records
SERDatabase::insertRecords() For storing parsed records
Sanitize a single SER text line by stripping Telnet and ANSI artefacts.
Removes Telnet IAC sequences (0xFF …), ANSI CSI escape sequences (ESC [ …), and non-printable control characters while keeping ordinary printable ASCII and horizontal tabs. A doubled IAC (0xFF 0xFF) is collapsed and discarded rather than emitted.
Parameters
line Raw line received from the Telnet session.
Returns
std::string Cleaned line suitable for field parsing.
Note
The function preserves tab characters (\t) so column-aligned relay output stays parsable.
Definition at line 212 of file ser_record.hpp.
Referenced by parseSERResponse().