Telnet-SML: RetryState Struct Reference
RetryState Struct Reference
Retry state management.
#include <telnet_fsm.hpp>
Public Member Functions
bool canRetry () const
Check if more retry attempts are available.
void reset ()
Reset retry counter to zero.
void increment ()
Increment retry counter.
Public Attributes
int max_retries = 3
Maximum retry attempts allowed.
int current_attempt = 0
Current attempt counter.
std::chrono::seconds retry_delay {30}
Delay between retry attempts.
Detailed Description
Retry state management.
Tracks retry attempts for authentication failures. Modified by RetryWaitAction and ResetRetryAction.
Retry Flow
Definition at line 194 of file telnet_fsm.hpp.
Member Function Documentation
canRetry()
bool RetryState::canRetry () const inline
Check if more retry attempts are available.
Returns
true if current_attempt < max_retries
Definition at line 204 of file telnet_fsm.hpp.
References current_attempt, and max_retries.
Referenced by CanRetryGuard::operator()(), and MaxRetriesReachedGuard::operator()().
increment()
void RetryState::increment () inline
Increment retry counter.
Postcondition
current_attempt increased by 1
Definition at line 216 of file telnet_fsm.hpp.
References current_attempt.
Referenced by RetryWaitAction::operator()().
reset()
void RetryState::reset () inline
Reset retry counter to zero.
Postcondition
current_attempt == 0
Definition at line 210 of file telnet_fsm.hpp.
References current_attempt.
Referenced by ResetRetryAction::operator()().
Member Data Documentation
current_attempt
int RetryState::current_attempt = 0
Current attempt counter.
Definition at line 197 of file telnet_fsm.hpp.
Referenced by canRetry(), increment(), RetryWaitAction::operator()(), and reset().
max_retries
int RetryState::max_retries = 3
Maximum retry attempts allowed.
Definition at line 196 of file telnet_fsm.hpp.
Referenced by canRetry(), and RetryWaitAction::operator()().
retry_delay
std::chrono::seconds RetryState::retry_delay {30}
Delay between retry attempts.
Definition at line 198 of file telnet_fsm.hpp.
Referenced by RetryWaitAction::operator()().
The documentation for this struct was generated from the following file:
telnet_fsm.hpp