Telnet-SML: SharedRingBuffer Class Reference
SharedRingBuffer Class Reference
Thread-safe MPMC ring buffer for variable-length binary payloads.
#include <shared_ring_buffer.hpp>
Classes
struct ReaderSlot
Per-reader state stored in shared memory.
struct SharedHeader
Shared-memory header placed at the start of the mapped region.
Public Types
enum class OpenMode { CreateOnly , OpenOnly , OpenOrCreate }
Controls how the shared-memory segment is opened.
using ReaderId = uint32_t
Opaque reader identifier returned by registerReader()
Public Member Functions
SharedRingBuffer (const std::string &name, std::size_t capacity_bytes, OpenMode mode=OpenMode::OpenOrCreate, bool remove_on_destroy=false)
Construct and map a shared ring buffer.
~SharedRingBuffer ()
Destroy the ring buffer and optionally remove the shared segment.
ReaderId registerReader ()
Register a new reader and obtain a ReaderId.
void unregisterReader (ReaderId id)
Unregister a reader, freeing its slot.
std::size_t capacity () const
Return the usable data capacity of the ring buffer in bytes.
bool write (const uint8_t *data, std::size_t len)
Write a variable-length payload into the ring buffer.
bool waitRead (ReaderId reader_id, std::vector< uint8_t > &out, std::atomic< bool > &stop_flag)
Blocking read for a specific registered reader.
void notifyAll ()
Wake all threads blocked in waitRead().
bool overwriteOccurred () const
Check whether any message has been dropped due to buffer overflow.
void clearOverwriteFlag ()
Reset the overwrite-occurred flag to false.
uint64_t dropCount () const
Return the total number of messages dropped since creation.
uint64_t totalWrites () const
Return the total number of messages successfully written.
uint64_t totalReads (ReaderId reader_id) const
Total reads performed by a specific reader.
uint32_t activeReaderCount () const
Number of currently registered (active) readers.
Static Public Member Functions
static bool remove (const std::string &name)
Remove a named shared-memory segment.
Static Public Attributes
static constexpr uint32_t kMaxReaders = 8U
Maximum number of concurrent readers supported.
static constexpr ReaderId kInvalidReader = UINT32_MAX
Sentinel value indicating an invalid / unregistered reader.
Private Member Functions
std::size_t maxPayloadSize () const
Maximum payload size for a single message.
std::size_t normalizePos (std::size_t pos) const
Clamp a position to a valid buffer offset.
std::size_t usedBytes (std::size_t readPos, std::size_t writePos) const
Bytes occupied between a read position and the write position.
std::size_t freeBytes (std::size_t readPos, std::size_t writePos) const
Available free space in the ring given a read and write position.
std::size_t effectiveReadPos (std::size_t writePos) const
Find the effective read position (slowest active reader).
uint32_t slowestReaderIndex (std::size_t writePos) const
Index of the slowest (most behind) active reader.
bool dropOldestForSlowest (std::size_t writePos)
Drop the oldest message for the slowest reader(s).
uint32_t readLength (std::size_t pos) const
Read a little-endian 32-bit message length from the buffer.
void writeLength (std::size_t pos, uint32_t len)
Write a little-endian 32-bit message length into the buffer.
Private Attributes
std::string name_
bool remove_on_destroy_ = false
boost::interprocess::shared_memory_object shm_
boost::interprocess::mapped_region region_
SharedHeader * header_ = nullptr
uint8_t * buffer_ = nullptr
Static Private Attributes
static constexpr std::size_t kHeaderSize = 4U
Size in bytes of the per-message length prefix.
static constexpr uint32_t kMagic = 0x4D524E47U
Magic number "MRNG" — identifies MPMC ring format.
Detailed Description
Thread-safe MPMC ring buffer for variable-length binary payloads.
Supports multiple producers writing concurrently and multiple consumers each receiving every message (broadcast pattern). Uses a single interprocess mutex for all synchronisation, suitable for both inter-thread and inter-process use.
Each reader gets its own cursor via registerReader(). The writer is constrained by the slowest active reader; when the buffer is full the oldest unread message is dropped for the slowest reader(s) and an overwrite flag is set.
Definition at line 66 of file shared_ring_buffer.hpp.
Member Typedef Documentation
ReaderId
using SharedRingBuffer::ReaderId = uint32_t
Opaque reader identifier returned by registerReader()
Definition at line 73 of file shared_ring_buffer.hpp.
Member Enumeration Documentation
OpenMode
enum class SharedRingBuffer::OpenMode strong
Controls how the shared-memory segment is opened.
Determines whether the constructor creates a new segment, opens an existing one, or does either depending on existence.
// Create a fresh ring, removing any previous one with the same name
SharedRingBuffer ring("MyRing", 64 * 1024, SharedRingBuffer::OpenMode::CreateOnly);
// Attach to an existing ring created by another process
SharedRingBuffer ring2("MyRing", 0, SharedRingBuffer::OpenMode::OpenOnly);
Enumerator
CreateOnly
Remove any existing segment and create a new one.
OpenOnly
Open an existing segment; throws if not found.
OpenOrCreate
Open if it exists, otherwise create a new one.
Definition at line 93 of file shared_ring_buffer.hpp.
Constructor & Destructor Documentation
SharedRingBuffer()
SharedRingBuffer::SharedRingBuffer (const std::string & name, std::size_t capacity_bytes, OpenMode mode = OpenMode::OpenOrCreate, bool remove_on_destroy = false) inline explicit
Construct and map a shared ring buffer.
Creates or opens a named shared-memory segment, maps it into the process address space, and initialises the header if the segment is newly created (detected via a magic number check).
Parameters
name Unique name for the shared-memory segment.
capacity_bytes Usable data capacity in bytes (excluding internal header).
mode How the segment is opened (default: OpenOrCreate).
remove_on_destroy If true, the segment is removed when this object is destroyed.
Exceptions
std::invalid_argument If name is empty or capacity_bytes is too small.
std::runtime_error If the segment exists but has a different capacity.
SharedRingBuffer ring("SER_Ring", 500U * 1024U,
                      SharedRingBuffer::OpenMode::CreateOnly, true);
Definition at line 741 of file shared_ring_buffer.hpp.
References buffer_, CreateOnly, header_, kHeaderSize, kMagic, kMaxReaders, name_, OpenOnly, region_, remove_on_destroy_, and shm_.
~SharedRingBuffer()
SharedRingBuffer::~SharedRingBuffer () inline
Destroy the ring buffer and optionally remove the shared segment.
If remove_on_destroy was set in the constructor, the underlying shared-memory object is unlinked so that subsequent open attempts by other processes will fail.
Definition at line 808 of file shared_ring_buffer.hpp.
References name_, and remove_on_destroy_.
Member Function Documentation
activeReaderCount()
uint32_t SharedRingBuffer::activeReaderCount () const inline
Number of currently registered (active) readers.
Definition at line 462 of file shared_ring_buffer.hpp.
References header_, and kMaxReaders.
capacity()
std::size_t SharedRingBuffer::capacity () const inline
Return the usable data capacity of the ring buffer in bytes.
This is the raw payload area, excluding the internal shared-memory header. Individual messages consume their payload size plus a 4-byte length prefix.
Returns
Data capacity in bytes.
SharedRingBuffer ring("Test", 1024);
assert(ring.capacity() == 1024);  // usable payload area
Definition at line 207 of file shared_ring_buffer.hpp.
References header_.
clearOverwriteFlag()
void SharedRingBuffer::clearOverwriteFlag () inline
Reset the overwrite-occurred flag to false.
Call after logging or handling the overwrite condition.
Note
Thread-safe.
Definition at line 405 of file shared_ring_buffer.hpp.
References header_.
dropCount()
uint64_t SharedRingBuffer::dropCount () const inline
Return the total number of messages dropped since creation.
Incremented each time write() has to discard the oldest unread message for the slowest reader.
Returns
Cumulative drop count.
Note
Thread-safe.
Definition at line 420 of file shared_ring_buffer.hpp.
References header_.
dropOldestForSlowest()
bool SharedRingBuffer::dropOldestForSlowest (std::size_t writePos) inline private
Drop the oldest message for the slowest reader(s).
Finds all active readers at the same (slowest) position and advances them past one message. This frees buffer space for new writes.
Parameters
writePos Current write position.
Returns
true if a message was dropped, false if nothing to drop.
Precondition
Called with mutex held.
Definition at line 647 of file shared_ring_buffer.hpp.
References header_, kHeaderSize, kMaxReaders, maxPayloadSize(), normalizePos(), readLength(), and slowestReaderIndex().
Referenced by write().
effectiveReadPos()
std::size_t SharedRingBuffer::effectiveReadPos (std::size_t writePos) const inline private
Find the effective read position (slowest active reader).
Returns the read_pos of the active reader with the most unread data. If no readers are active, returns writePos (all space is free).
Parameters
writePos Current (possibly wrapped) write position.
Returns
The read_pos that constrains the writer.
Precondition
Called with mutex held.
Definition at line 584 of file shared_ring_buffer.hpp.
References header_, kMaxReaders, normalizePos(), and usedBytes().
Referenced by write().
freeBytes()
std::size_t SharedRingBuffer::freeBytes (std::size_t readPos, std::size_t writePos) const inline private
Available free space in the ring given a read and write position.
Parameters
readPos Current reader cursor.
writePos Current writer cursor.
Returns
Free bytes available for new writes.
Definition at line 569 of file shared_ring_buffer.hpp.
References header_, and usedBytes().
Referenced by write().
maxPayloadSize()
std::size_t SharedRingBuffer::maxPayloadSize () const inline private
Maximum payload size for a single message.
Equals capacity minus the 4-byte length header. Any write exceeding this limit is rejected.
Returns
Max payload in bytes, or 0 if capacity is too small.
Definition at line 527 of file shared_ring_buffer.hpp.
References header_, and kHeaderSize.
Referenced by dropOldestForSlowest(), waitRead(), and write().
normalizePos()
std::size_t SharedRingBuffer::normalizePos (std::size_t pos) const inline private
Clamp a position to a valid buffer offset.
If pos extends past the last possible message start (capacity − 4), it wraps back to 0.
Parameters
pos Raw position value.
Returns
Normalised position within [0, capacity − kHeaderSize].
Definition at line 541 of file shared_ring_buffer.hpp.
References header_, and kHeaderSize.
Referenced by dropOldestForSlowest(), effectiveReadPos(), slowestReaderIndex(), waitRead(), and write().
notifyAll()
void SharedRingBuffer::notifyAll () inline
Wake all threads blocked in waitRead().
Typically called during shutdown so that consumers can re-check their stop flag and exit cleanly.
Definition at line 368 of file shared_ring_buffer.hpp.
References header_.
overwriteOccurred()
bool SharedRingBuffer::overwriteOccurred () const inline
Check whether any message has been dropped due to buffer overflow.
Returns true if write() had to advance a slow reader past an unread message to make room. The flag is sticky — it stays true until explicitly cleared with clearOverwriteFlag().
Returns
true if at least one overwrite has occurred.
Note
Thread-safe.
if (ring.overwriteOccurred()) {
    std::cerr << "Warning: " << ring.dropCount() << " messages dropped\n";
    ring.clearOverwriteFlag();
}
Definition at line 393 of file shared_ring_buffer.hpp.
References header_.
readLength()
uint32_t SharedRingBuffer::readLength (std::size_t pos) const inline private
Read a little-endian 32-bit message length from the buffer.
Decodes the 4-byte length prefix stored at pos.
Parameters
pos Byte offset within the data area.
Returns
Decoded payload length.
Precondition
pos + 4 ≤ capacity.
Definition at line 708 of file shared_ring_buffer.hpp.
References buffer_.
Referenced by dropOldestForSlowest(), and waitRead().
registerReader()
ReaderId SharedRingBuffer::registerReader () inline
Register a new reader and obtain a ReaderId.
The new reader's cursor starts at the current write position, so it will only see messages written after registration.
Returns
ReaderId on success, kInvalidReader if all slots are full.
Note
Thread-safe.
Definition at line 161 of file shared_ring_buffer.hpp.
References header_, kInvalidReader, and kMaxReaders.
remove()
bool SharedRingBuffer::remove (const std::string & name) inline static
Remove a named shared-memory segment.
Unlinks the shared-memory object identified by name. Useful for manual cleanup when the ring was not created with remove_on_destroy.
Parameters
name The segment name passed to the constructor.
Returns
true if the segment was removed, false otherwise.
SharedRingBuffer::remove("SER_Ring");  // clean up from a previous run
Definition at line 816 of file shared_ring_buffer.hpp.
slowestReaderIndex()
uint32_t SharedRingBuffer::slowestReaderIndex (std::size_t writePos) const inline private
Index of the slowest (most behind) active reader.
Parameters
writePos Current write position.
Returns
Reader index [0..kMaxReaders), or kMaxReaders if none active.
Precondition
Called with mutex held.
Definition at line 617 of file shared_ring_buffer.hpp.
References header_, kMaxReaders, normalizePos(), and usedBytes().
Referenced by dropOldestForSlowest().
totalReads()
uint64_t SharedRingBuffer::totalReads (ReaderId reader_id) const inline
Total reads performed by a specific reader.
Parameters
reader_id ReaderId to query.
Returns
Read count, or 0 if reader_id is invalid.
Definition at line 451 of file shared_ring_buffer.hpp.
References header_, and kMaxReaders.
totalWrites()
uint64_t SharedRingBuffer::totalWrites () const inline
Return the total number of messages successfully written.
Monotonically increasing counter, useful for throughput monitoring.
Returns
Cumulative write count.
Note
Thread-safe.
std::cout << "Writes: " << ring.totalWrites()
          << "  Drops: " << ring.dropCount() << '\n';
Definition at line 439 of file shared_ring_buffer.hpp.
References header_.
unregisterReader()
void SharedRingBuffer::unregisterReader (ReaderId id) inline
Unregister a reader, freeing its slot.
Parameters
id ReaderId previously returned by registerReader().
Note
Thread-safe. Safe to call with kInvalidReader (no-op).
Definition at line 183 of file shared_ring_buffer.hpp.
References header_, and kMaxReaders.
usedBytes()
std::size_t SharedRingBuffer::usedBytes (std::size_t readPos, std::size_t writePos) const inline private
Bytes occupied between a read position and the write position.
Parameters
readPos Current reader cursor.
writePos Current writer cursor.
Returns
Number of bytes that have been written but not yet read.
Definition at line 555 of file shared_ring_buffer.hpp.
References header_.
Referenced by effectiveReadPos(), freeBytes(), and slowestReaderIndex().
waitRead()
bool SharedRingBuffer::waitRead (ReaderId reader_id, std::vector< uint8_t > & out, std::atomic< bool > & stop_flag) inline
Blocking read for a specific registered reader.
Blocks until a payload is available for this reader or stop_flag becomes true. Each reader maintains its own cursor and receives every message independently.
Parameters
reader_id ReaderId from registerReader().
out Output vector filled with payload bytes.
stop_flag Atomic flag; set to true to unblock and return false.
Returns
true if a payload was read, false on stop or error.
Note
Thread-safe.
Definition at line 293 of file shared_ring_buffer.hpp.
References SharedRingBuffer::ReaderSlot::active, buffer_, header_, kHeaderSize, kMaxReaders, maxPayloadSize(), normalizePos(), SharedRingBuffer::ReaderSlot::read_pos, readLength(), and SharedRingBuffer::ReaderSlot::total_reads.
write()
bool SharedRingBuffer::write (const uint8_t * data, std::size_t len) inline
Write a variable-length payload into the ring buffer.
Multiple threads/processes may call write() concurrently. If the buffer is full (constrained by the slowest reader), the oldest message is dropped to make room. All readers at that oldest position are advanced past the dropped message.
Parameters
data Pointer to payload bytes.
len Number of bytes to write.
Returns
true on success, false if data is null, len is 0, or len exceeds capacity.
Note
Thread-safe.
Definition at line 227 of file shared_ring_buffer.hpp.
References buffer_, dropOldestForSlowest(), effectiveReadPos(), freeBytes(), header_, kHeaderSize, maxPayloadSize(), normalizePos(), and writeLength().
writeLength()
void SharedRingBuffer::writeLength (std::size_t pos, uint32_t len) inline private
Write a little-endian 32-bit message length into the buffer.
Encodes len as a 4-byte prefix at pos, used by write() before copying the payload bytes.
Parameters
pos Byte offset within the data area.
len Payload length to encode.
Precondition
pos + 4 ≤ capacity.
Definition at line 728 of file shared_ring_buffer.hpp.
References buffer_.
Referenced by write().
Member Data Documentation
buffer_
uint8_t* SharedRingBuffer::buffer_ = nullptr private
Definition at line 515 of file shared_ring_buffer.hpp.
Referenced by readLength(), SharedRingBuffer(), waitRead(), write(), and writeLength().
header_
SharedHeader* SharedRingBuffer::header_ = nullptr private
Definition at line 514 of file shared_ring_buffer.hpp.
Referenced by activeReaderCount(), capacity(), clearOverwriteFlag(), dropCount(), dropOldestForSlowest(), effectiveReadPos(), freeBytes(), maxPayloadSize(), normalizePos(), notifyAll(), overwriteOccurred(), registerReader(), SharedRingBuffer(), slowestReaderIndex(), totalReads(), totalWrites(), unregisterReader(), usedBytes(), waitRead(), and write().
kHeaderSize
std::size_t SharedRingBuffer::kHeaderSize = 4U static constexpr private
Size in bytes of the per-message length prefix.
Definition at line 476 of file shared_ring_buffer.hpp.
Referenced by dropOldestForSlowest(), maxPayloadSize(), normalizePos(), SharedRingBuffer(), waitRead(), and write().
kInvalidReader
ReaderId SharedRingBuffer::kInvalidReader = UINT32_MAX static constexpr
Sentinel value indicating an invalid / unregistered reader.
Definition at line 76 of file shared_ring_buffer.hpp.
Referenced by registerReader().
kMagic
uint32_t SharedRingBuffer::kMagic = 0x4D524E47U static constexpr private
Magic number "MRNG" — identifies MPMC ring format.
Definition at line 508 of file shared_ring_buffer.hpp.
Referenced by SharedRingBuffer().
kMaxReaders
uint32_t SharedRingBuffer::kMaxReaders = 8U static constexpr
Maximum number of concurrent readers supported.
Definition at line 70 of file shared_ring_buffer.hpp.
Referenced by activeReaderCount(), dropOldestForSlowest(), effectiveReadPos(), registerReader(), SharedRingBuffer(), slowestReaderIndex(), totalReads(), unregisterReader(), and waitRead().
name_
std::string SharedRingBuffer::name_ private
Definition at line 510 of file shared_ring_buffer.hpp.
Referenced by SharedRingBuffer(), and ~SharedRingBuffer().
region_
boost::interprocess::mapped_region SharedRingBuffer::region_ private
Definition at line 513 of file shared_ring_buffer.hpp.
Referenced by SharedRingBuffer().
remove_on_destroy_
bool SharedRingBuffer::remove_on_destroy_ = false private
Definition at line 511 of file shared_ring_buffer.hpp.
Referenced by SharedRingBuffer(), and ~SharedRingBuffer().
shm_
boost::interprocess::shared_memory_object SharedRingBuffer::shm_ private
Definition at line 512 of file shared_ring_buffer.hpp.
Referenced by SharedRingBuffer().
The documentation for this class was generated from the following file:
shared_memory/shared_ring_buffer.hpp